### ISSUE TITLE
Having issue while fetching the kubeconfig file

### ISSUE THREAD

**Issue by hareeshdsinfo** [Azure/terraform-azurerm-aks#104]
Having issue while fetching the kubeconfig file

**Comment by nitinnbisht** [comment]
Hi @hareeshdsinfo 

May you provide more details, what kind of issue are facing?

What arguments are you passing to the module?

**Comment by lonegunmanb** [comment]
I'm closing this issue since we've got no response from the user, we can fetch kubeconfig file via output `kube_config_raw`. Please feel free to reopen this issue if you have any further question @hareeshdsinfo.
