### ISSUE TITLE
Cannot override cluster location

### ISSUE THREAD

**Issue by larryclaman** [Azure/terraform-azurerm-aks#105]
cluster location defaults to using resource group location, and there's no way to override this.
Creating PR to address this.

**Comment by kdouglas-qarik** [comment]
I'm seeing an issue with this where my plan/apply is destroying/recreating the cluster every time since the location is 'known after apply'. Would be great to get this PR merged to prevent this occuring.

**Comment by nitinnbisht** [comment]
@larryclaman and @kdouglas-qarik: I think [this PR ](https://github.com/Azure/terraform-azurerm-aks/pull/102)already solves this and more, as the resource recreation issue due to data source lookup not only affects AKS creation but loganalytics resource as well.

I understand the intention here is to allow creating AKS cluster in a different location, but the linked PR addresses that as well. Please have a look.

**Comment by larryclaman** [comment]
I'll happily defer (close)  my simple change  in PR #106 to the broader changes in PR #102 if #102 fixes a broader set of problems.

I like the fix proposed in 102, but an open question to terraform exports:  is it really the case that reading a value (location) from a data resource will always force a recreation?  Seems like a bug that terraform cannot determine that the location is not changing, and that the only workaround this is to put the location in a variable.

**Comment by kdouglas-qarik** [comment]
Ah, yes, I hadn't see https://github.com/Azure/terraform-azurerm-aks/pull/102 but that does also solve the issue with the log analytics resources which I was also seeing.

**Comment by pearcec** [comment]
Hi @yupwei68,  without this override it makes the module difficult to develop with.  Any chance we can get a release with one of the two proposed solutions?

**Comment by pearcec** [comment]
Reading this issue https://github.com/Azure/terraform-azurerm-network/issues/58  if you  drop`depends_on = [module.network]` from the module, this eliminates the destroy/create cycle.  (Working off the README.md example).  The depends_on is not necessary and is forcing a runtime evaluation of the location.

**Comment by lonegunmanb** [comment]
Sorry for the late reply, I'm closing this issue in favor of #172 has brought us this feature. Thank you for your understanding.
