### ISSUE TITLE
 user_assigned_identity_id is not expected

### ISSUE THREAD

**Issue by ghost** [Azure/terraform-azurerm-aks#110]
```
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/aks/main.tf line 81, in resource "azurerm_kubernetes_cluster" "main":
│   81:       user_assigned_identity_id = var.user_assigned_identity_id
│ 
│ An argument named "user_assigned_identity_id" is not expected here.
```

Hi I have tried to find many work arounds assigning null to the argument, but the only thing that seems to work is to remove the argument from the module. 

I am using ` identity_type = "SystemAssigned" ` , with no client_id nor client_secret.

**Comment by zioproto** [comment]
I am not able to reproduce this issue. 
Because the user that opened the issue is "ghost" I would say this issue is stale and should be closed.

**Comment by lonegunmanb** [comment]
Close since cannot reproduce the issue.
