### ISSUE TITLE
Expose `os_disk_type` as a variable

### ISSUE THREAD

**Issue by wjam-hanzo** [Azure/terraform-azurerm-aks#114]
I've just spun up a Kubernetes cluster in Azure using this module and am reviewing the advisor recommendations. One of the recommendations is to switch to [emphemeral OS disks](https://docs.microsoft.com/en-gb/azure/aks/cluster-configuration?WT.mc_id=Portal-Microsoft_Azure_Expert#ephemeral-os), which would be achieved by setting the `os_disk_type` argument for the `default_node_pool` block to `Ephemeral` from the default `Managed`.

Please add a variable to be able to switch OS disk types to make use of this feature.

**Comment by lebenitza** [comment]
@jcorioland can this get some attention please?
