### ISSUE TITLE
Problem with ingress_application_gateway add_on

### ISSUE THREAD

**Issue by tmiroslav** [Azure/terraform-azurerm-aks#117]
There is problem with ingress_application_gateway add on functionality. This is part of code I use for creation of AKS cluster
```
addon_profile {
    ingress_application_gateway {
      enabled    = true
      gateway_name = "appgw-clusters"
      subnet_cidr  = var.appgw_address_prefix
    }
  }
```
App gw will be created only when for identity service principal is  defined 
```
service_principal {
    client_id     = var.azure_client_id
    client_secret = var.azure_client_secret
}

```
But, in that case, after I deploy ingress in the cluster, it is not getting IP!

When , for identity is set managed identity
```
identity {
    type = "SystemAssigned"
```
App gw will not be created. 
And interesting thing is, when I run code while service principal is set as identity, and then change identity to be `SystemAssigned`
and run such code again, then everything is working as expected.

How creation of app gw using add-on is impacted by identity setup in the AKS?  I use terraform 13, and azurerm_kubernetes_cluster resource to create AKS cluster.

Thanx,
Miroslav

**Comment by kandreasyan-korio** [comment]
This is the minimum configuration to create AGIC for SystemAssigned identity. 

`ingress_application_gateway_enabled = true
  ingress_application_gateway_name      = format("%s-%s", local.name_prefix, "aks-agw")
  ingress_application_gateway_subnet_id = lookup(module.vnet.vnet_subnets_name_id, "aks-agw-snet")
  network_contributor_role_assigned_subnet_ids = {
    aks-agw-snet = lookup(module.vnet.vnet_subnets_name_id, "aks-agw-snet")
  }`

**Comment by zioproto** [comment]
Hello Miroslav,

do I understand correctly you are **not** using the [AKS module](https://registry.terraform.io/modules/Azure/aks/azurerm/latest) ?

Please if you are using the `azurerm_kubernetes_cluster` resource directly you might want to open an issue on the provider repository:
https://github.com/hashicorp/terraform-provider-azurerm

thank you

**Comment by lonegunmanb** [comment]
I'm closing this issue since no user response received. Please feel free to reopen it once you have any further details, thanks @tmiroslav !
