### ISSUE TITLE
Improving upgrading logic for node pools

### ISSUE THREAD

**Issue by rdvansloten** [Azure/terraform-azurerm-aks#118]
Hi,

When wanting to upgrade/alter the default node pool, Terraform will trigger a complete cluster destroy. We now work around this by:

- Creating a temporary node pool
- Drain the default node pool
- Delete the default node pool manually
- Create a new node pool with the desired settings with the same name
- Migrate the temp node pool back to the default node pool

Could this sequence be something that Terraform could handle for people? One wouldn't often edit the default node pool, but sometimes it is necessary for cost savings, or when MS introduces new features (like Managed -> Ephemeral Storage)

**Comment by Wittionary** [comment]
I support this idea, but have no clue what it would take to make this happen.

**Comment by lonegunmanb** [comment]
I'm closing this issue since we've merged #334. Please feel free to reopen it if you have any different thoughts. Thanks for your contribution.
