### ISSUE TITLE
Add support for attaching Azure Container Registries

### ISSUE THREAD

**Issue by hairmare** [Azure/terraform-azurerm-aks#119]
Hi we would like to attach an ACR isntance to a cluster, both at creation time or as an update as per [these docs](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration).

It would be nice if the module would support both these use cases:

1. Create a new AKS cluster with ACR integration
```bash
# set this to the name of your Azure Container Registry.  It must be globally unique
MYACR=myContainerRegistry

# Run the following line to create an Azure Container Registry if you do not already have one
az acr create -n $MYACR -g myContainerRegistryResourceGroup --sku basic

# Create an AKS cluster with ACR integration
az aks create -n myAKSCluster -g myResourceGroup --generate-ssh-keys --attach-acr $MYACR
```
2. Configure ACR integration for existing AKS clusters
```bash
az aks update -n myAKSCluster -g myResourceGroup --attach-acr <acr-name>
```

I've recently seen an uptick in ACR usage so this might be something you would want to prioritize. I haven't checked if the terraform provider already supports this.

**Comment by lonegunmanb** [comment]
This feature has been implemented by #298 so I'm closing this issue now, please feel free to reopen it if you have any further question, thanks!
