### ISSUE TITLE
Allow RBAC for K8s Service Accounts with out the need for AzureAD 

### ISSUE THREAD

**Issue by manoatsas** [Azure/terraform-azurerm-aks#137]
Allow Kubernetes RBAC to be enabled to use Kubernetes Service Accounts with out the need for AzureAD integration per docs
- Azurerm TF provider - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#role_based_access_control, `azure_active_directory` is optional for `role_based_access_control` block
- Azure docs - https://docs.microsoft.com/en-us/azure/aks/concepts-identity#azure-role-based-access-control 

However, when `enable_role_based_access_control = true` and with default `rbac_aad_managed=false` currently it fails with the error
```
│ Error: You must specify client_app_id and server_app_id and server_app_secret when using managed aad rbac (managed = false)
│ 
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on .terraform/modules/aks/main.tf line 10, in resource "azurerm_kubernetes_cluster" "main":
│   10: resource "azurerm_kubernetes_cluster" "main" {
```

**Comment by zioproto** [comment]
The `role_based_access_control` block is deprecated in favour of the `role_based_access_control_enabled` property and the `azure_active_directory_role_based_access_control` block.

@manoatsas I struggle to understand the configuration you would like to see in the module.

Can you provide a working example of the resulting `azurerm_kubernetes_cluster` resource that would like the module to produce ?

thanks

**Comment by lonegunmanb** [comment]
I'm closing this issue since no response from the user, please feel free to reopen it if you have any further question @manoatsas.
