### ISSUE TITLE
Add support for limiting public IP ranges to Kubernetes management API

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [Azure/terraform-azurerm-aks#138]
Add support for this attribute in the k8s cluster: -

api_server_authorized_ip_ranges

**Comment by Vinaum8** [comment]
this problem is resolved on version 7

**Comment by lonegunmanb** [comment]
Thanks @Vinaum8 for the update, I'm closing this issue since the feature has been implemented in #220. Please feel free to reopen it if you have any further question @MarkRoss-Eviden
