### ISSUE TITLE
add outputs for azurerm_kubernetes_cluster.main.addon_profile

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-aks#142]
Can you add outputs for `azurerm_kubernetes_cluster.main.addon_profile`
This is required in order to get the principalids in `module.aks.addon_profile[0].ingress_application_gateway[0].ingress_application_gateway_identity[0].object_id` and `module.aks.addon_profile[0].ingress_application_gateway[0].gateway_id` in order to do role_assignments on the app gw and the app gw resource group in order to make AGIC work.

**Comment by lonegunmanb** [comment]
Sorry for the late reply @davidkarlsen, I'm closing this issue since the provider 3.x has re-designed the `addon_profile` block, and we've exported some addons in outputs. Please feel free to open new issues if you find some missing parts that you need, and thanks for your understanding.

**Comment by davidkarlsen** [comment]
NP - no need for this any longer!
