### ISSUE TITLE
Supporting CSI driver addon

### ISSUE THREAD

**Issue by gevraud-cicd** [Azure/terraform-azurerm-aks#143]
Hello, 

I would like to integrate AKS with AKV . I saw there is an csi-driver addon to enable in AKS.

But I don't see this feature in the module .

Is it planned to do it ?

Regards

**Comment by lonegunmanb** [comment]
Hi, @gevraud-cicd sorry for this crazy late reply and thanks for open this issue, would you please give me an url to this csi-driver's Terraform AzureRM Provider document so I can see what I can do for this issue? Thanks for your understanding.

**Comment by davidkarlsen** [comment]
I think this is already supported with this param:
```
  key_vault_secrets_provider_enabled = true
```

**Comment by davidkarlsen** [comment]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#key_vault_secrets_provider

**Comment by lonegunmanb** [comment]
Apology for the late reply, I'm closing this issue because the feature has been implemented in #214, please feel free to reopen it if you have any further question, thanks!
