### ISSUE TITLE
Add output for kube_admin_config_raw

### ISSUE THREAD

**Issue by RobMokkink** [Azure/terraform-azurerm-aks#147]
See pull request [146](https://github.com/Azure/terraform-azurerm-aks/pull/146)
I would like to have an output for ```kube_admin_config_raw```, so day 2 operations can be automated easily.

Thanks.

**Comment by lonegunmanb** [comment]
Sorry for the late reply @RobMokkink , we've brought this feature in #146 so I'm closing this issue now. Thanks for your understanding.
