### ISSUE TITLE
Allow taints for default (system) pool

### ISSUE THREAD

**Issue by ealasgarov** [Azure/terraform-azurerm-aks#152]
Currently it's not possible to taint System pool (default agent's pool) within the module.

Please allow for the parameter: [only_critical_addons_enabled = bool] or at least just a taint block to be added, e.g. 

agent_taints = [
    "CriticalAddonsOnly=true:NoSchedule"
  ]

Existing nodepools cannot be tainted after creation, only the single nodes within them.

**Comment by carvido1** [comment]
Hello.
We are facing the same issue. It would be nice to taint the nodepools directly with the cluster creation.
This is a recommendation from Microsoft documentation when using (user and system nodepools)[https://docs.microsoft.com/en-us/azure/aks/use-system-pools#system-and-user-node-pools]
KR

**Comment by lonegunmanb** [comment]
Hi @ealasgarov , unfortunately as I've explained in #163:

>The AKS API has removed support for tainting all nodes in the default node pool and it is no longer possible to configure this. To taint a node pool, create a separate one.

So I think it's impossible to taint the default node pool. Thanks for opening this issue.

**Comment by terrymunro** [comment]
@lonegunmanb What about that parameter @ealasgarov mentioned: [kubernetes_cluster#only_critical_addons_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#only_critical_addons_enabled)

It is strange that the error message says it's been removed but then [a few lines later](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_nodepool.go#L625-L632) it adds one in anyway.
Is that one an exception, a bug, or lies? 🤷

**Comment by lonegunmanb** [comment]
I'm closing this issue since we can taint default node pool since #129 introduced new variable `only_critical_addons_enabled`.
