### ISSUE TITLE
Rerunning terraform configuration forces cluster to be replaced

### ISSUE THREAD

**Issue by ealasgarov** [Azure/terraform-azurerm-aks#155]
When I'm rerunning the terraform configuration in "plan" I can see that the cluster will be replaced due to:
```   ~ location                            = "westeurope" -> (known after apply) # forces replacement ```

In the module I can see: ``` location   = data.azurerm_resource_group.main.location ```

My resource group didn't change. Just to be sure I've removed it from the state and reimported again, but it didn't help. 

My resource group:

``` resource "azurerm_resource_group" "platform-aks" { ```
```  name     = "platform-aks" ```
```  location = "West Europe" ```  

(I've tried to writing "westeurope" instead, same result)

In my module resource group is defined like that:
```  module "aks" { ```
```  source                           = "Azure/aks/azurerm" ```
```  version                          = "4.14.0" ```
```  resource_group_name  = azurerm_resource_group.platform-aks.name ```

Did anyone encounter anything like that, how to go around this problem?

Thanks in advance!

**Comment by lonegunmanb** [comment]
The datasource's attribute is "Known after apply", which means it could change anytime. If you assign a datasource's attribute to a `ForceNew` argument, yes, it would cause recreate every time.

Is that possible to use variable as the location?

**Comment by ealasgarov** [comment]
As a workaround, I have downloaded the module and referenced it as a local module instead. In the module I've set a "hardcoded" value for my location "westeurope". This is not ideal, but whatever.

**Comment by lonegunmanb** [comment]
@ealasgarov Thanks for the updating. Can we close this issue now?
