### ISSUE TITLE
Additional node pools are completely replaced if vnet_subnet_id is not specified

### ISSUE THREAD

**Issue by chmura-werdna** [Azure/terraform-azurerm-aks#160]
If the `vnet_subnet_id` is not specified in the `azurerm_kubernetes_cluster_node_pool` resource block, the provider will force a replacement of the entire node pool when the terraform script is applied to the AKS cluster. 

For example, here I am attempting to scale up the `additional_node_pool` from 3 to 4 nodes. Terraform will then completely destroy the additional node pool resource and build a new node pool with the 4 nodes. If I specify the vnet_subnet_id in the resource block for the additional node pool, this does not occur and the node pool scales up accordingly. The same pattern of behavior occurs during a scale down operation.

This is the example output that appears:

```
Terraform will perform the following actions:

  # azurerm_kubernetes_cluster_node_pool.additional_node_pool must be replaced
-/+ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pool" {
      - enable_auto_scaling    = false -> null
      - enable_host_encryption = false -> null
      - enable_node_public_ip  = false -> null
      - fips_enabled           = false -> null
      ~ id                     = "/subscriptions/subscription-id-guid/resourceGroups/myResourceGroupName/providers/Microsoft.ContainerService/managedClusters/aksClusterName/agentPools/additional_node_pool" -> (known after apply)
      ~ kubelet_disk_type      = "OS" -> (known after apply)
      - max_count              = 0 -> null
      ~ max_pods               = 30 -> (known after apply)
      - min_count              = 0 -> null
        name                   = "additional_node_pool"
      ~ node_count             = 3 -> 4
      ~ node_labels            = {} -> (known after apply)
      - node_taints            = [] -> null
      ~ orchestrator_version   = "1.22.6" -> (known after apply)
      ~ os_disk_size_gb        = 128 -> (known after apply)
      ~ os_sku                 = "Ubuntu" -> (known after apply)
        tags                   = {
            "environment" = "Demo"
            "purpose"     = "example"
        }
      - vnet_subnet_id         = "/subscriptions/subscription-id-guid/resourceGroups/myResourceGroupName/providers/Microsoft.Network/virtualNetworks/MY-VNET/subnets/aksCluster-subnet" -> null # forces replacement
      - zones                  = [] -> null
        # (9 unchanged attributes hidden)
    }
```

**Comment by lonegunmanb** [comment]
@chmura-werdna Thanks for opening this issue. The plan described the reason why the node pool was recreated, I think when we add this node pool to a cluster, the node pool's `vnet_subnet_id` was set to the cluster's subnet's id in the service side, out of Terraform's lifecycle. When you run plan, the Terraform detect the config's drift, and since the `vnet_subnet_id` argument is `ForceNew`, an unnecessary replacement happened. I think maybe we should make `vnet_subnet_id` a required argument, but it's an azurerm provider's issue, as for this module we have nothing to do with that.

**Comment by chmura-werdna** [comment]
Thank you, @lonegunmanb - I agree that `vnet_subnet_id` should probably be a required argument on the node pool block.
