### ISSUE TITLE
As is module failed to create a cluster

### ISSUE THREAD

**Issue by aku163** [Azure/terraform-azurerm-aks#19]
There are multiple issues which are identified as part of consumption to 1.0.0 module.

1. Leaving default `prefix` variable value to `cluster` name fails to create the cluster as it is not unique name for log analytics resource. have overridden with additional property value.

2. Running with above state it resulted in below failure. Need to override variable `kubernetes_version` . Instruction sets needs to get updated for mandatory values in order to support as is usage of the module.

```
* module.aks.module.kubernetes.azurerm_kubernetes_cluster.main: 1 error(s) occurred:

* azurerm_kubernetes_cluster.main: Error creating/updating Managed Kubernetes Cluster "aksclustermodule-aks" (Resource Group "aksclustermodule-resources"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The value of parameter orchestratorProfile.OrchestratorVersion is invalid. Please see https://aka.ms/aks-naming-rules for more details." Target="orchestratorProfile.OrchestratorVersion"
```

**Comment by n01d** [comment]
Updated the module with https://github.com/Azure/terraform-azurerm-aks/commit/25543c6bf259509fd1d9071e47acc3875cc39c1d and https://github.com/Azure/terraform-azurerm-aks/commit/be16e1c0bd993e4df39ea0ea24ce045da17a6aa5 to avoid these issues and have the latest Kubernetes version being used. I will update the readme as well.
