### ISSUE TITLE
Can't use role_based_access_control without azure_active_directory

### ISSUE THREAD

**Issue by a-kulik** [Azure/terraform-azurerm-aks#215]
Hi, in the lates version - 4.16.0, there is no ability to deploy AKS with only RBAC and without AAD, there is no option to disable "AKS-managed AAD"  only if also disable RBAC
It will always create "azure_active_directory" even "rbac_aad_managed = false" 
```
    dynamic "azure_active_directory" {
      for_each = var.enable_role_based_access_control && var.rbac_aad_managed ? ["rbac"] : []
      content {
        managed                = true
        admin_group_object_ids = var.rbac_aad_admin_group_object_ids
      }
    }

    dynamic "azure_active_directory" {
      for_each = var.enable_role_based_access_control && !var.rbac_aad_managed ? ["rbac"] : []
      content {
        managed           = false
        client_app_id     = var.rbac_aad_client_app_id
        server_app_id     = var.rbac_aad_server_app_id
        server_app_secret = var.rbac_aad_server_app_secret
      }
    }
```

**Comment by a-kulik** [comment]
Hi @lonegunmanb, you can use AKS with rbac only:
`Role-based access control (RBAC) is a method of regulating access to computer or network resources based on the roles of individual users within your organization.`
Or you can optionally add azure AD:
`Azure AD can only be enabled on Kubernetes RBAC-enabled cluster.
Azure Kubernetes Service (AKS) can be configured to use Azure Active Directory (AD) for user authentication. In this configuration, you sign in to an AKS cluster using an Azure AD authentication token. Once authenticated, you can use the built-in Kubernetes role-based access control (Kubernetes RBAC) to manage access to namespaces and cluster resources based on a user's identity or group membership.`
So you can only use RBAC without AD.

RBAC authorization uses the rbac.authorization.k8s.io [API group](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups-and-versioning) to drive authorization decisions, allowing you to dynamically configure policies through the Kubernetes API.

**Comment by DPatrickBoyd** [comment]
> Hi @lonegunmanb, you can use AKS with rbac only: `Role-based access control (RBAC) is a method of regulating access to computer or network resources based on the roles of individual users within your organization.` Or you can optionally add azure AD: `Azure AD can only be enabled on Kubernetes RBAC-enabled cluster. Azure Kubernetes Service (AKS) can be configured to use Azure Active Directory (AD) for user authentication. In this configuration, you sign in to an AKS cluster using an Azure AD authentication token. Once authenticated, you can use the built-in Kubernetes role-based access control (Kubernetes RBAC) to manage access to namespaces and cluster resources based on a user's identity or group membership.` So you can only use RBAC without AD.

If you aren't use AAD, how are you managing RBAC?

**Comment by balonik** [comment]
@DPatrickBoyd using the built-in Kubernetes RBAC

**Comment by zioproto** [comment]
Looking at:
https://learn.microsoft.com/en-us/azure/aks/concepts-identity

If I understand correctly `var.rbac_aad_azure_rbac_enabled = true` requires also `var.role_based_access_control_enabled = true`. This is also what is suggested from create an AKS cluster in the portal.

<img width="881" alt="Screenshot 2022-10-18 at 08 16 18" src="https://user-images.githubusercontent.com/789701/196350586-e78a52ab-d66f-44ae-8659-b60249f42f79.png">

**Comment by zioproto** [comment]
@a-kulik would the changes proposed in #269 fix the problem ?
