### ISSUE TITLE
Unable to Scale up the existing node pool/cluster

### ISSUE THREAD

**Issue by sourabhsharma-devsecops-specialist** [Azure/terraform-azurerm-aks#227]
Description: By using this code from the master branch, I'm able to deploy the AKS cluster, whilst, I'm unable to scale you the nodes from X to X+N (for example: X = 2, and N = 4) using enable_auto_scaling set to true having min_count and max_count.

When I try this, so instead of scaling up the node/node pool, cluster gets destroyed first and then create the new cluster from scratch.

Branch: Master

`
terraform version: Terraform v1.2.6

az version: 
{
  "azure-cli": "2.38.0",
  "azure-cli-core": "2.38.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

azurerm: v3.17.0
`

_Even when I try to scale up the use node pool, the whole cluster gets recreated from scratch_

Please let me know in case you need more information to fix this?

**Comment by lonegunmanb** [comment]
Hi @sourabhsharma-devsecops-specialist , thanks for opening this issue. Would you please:

1. Paste a minimum sample code that could reproduce your issue
2. Describe your operations sequence
3. Paste the Terraform plan you've seen

Thanks for your patience and cooperation.

**Comment by sourabhsharma-devsecops-specialist** [comment]
Hi @lonegunmanb - I'm happy to confirm that with latest code release, I'm able to scale-up/down the nodes without destroying the cluster. Thanks!
