### ISSUE TITLE
Support linux_os_config in AKS module

### ISSUE THREAD

**Issue by levya4** [Azure/terraform-azurerm-aks#239]
I would like to have the `linux_os_config` option in the AKS module.
[See docs](https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration#linux-os-custom-configuration)
Thanks

**Comment by lonegunmanb** [comment]
Hi @levya4 thanks for opening this issue, I agree it'll be great if we can have this block in this module, but now we're working to add a CI pipeline for this repo so we'd like to continue our bugfix and adding new feature after that. Thanks for your understanding, I'll try to add this feature asap.
