### ISSUE TITLE
Support for load_balancer_profile

### ISSUE THREAD

**Issue by mielmat** [Azure/terraform-azurerm-aks#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,
I would like to know if there is a possibility to extend this module and make load balancer configuration exposed to variable? That would help a lot with a bit more specific cases, like to use already existing public IP to avoid recreation it in case of cluster recreation. This is exposed in `azurerm_kubernetes_cluster` resource, but this module didn't expose that.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by zioproto** [comment]
Hello @mielmat 

You are talking about specify the outbound IPs like described in this doc page ?

https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#create-the-cluster-with-your-own-public-ip-or-prefixes

Could you make an example of the `azurerm_kubernetes_cluster` configuration that you are not able to achieve with the module ? 

Thanks

**Comment by mielmat** [comment]
Hello @zioproto,
that's exactly our case - and from what I see, it is not possible to achieve it with this module.

I'm not sure what kind of configuration should I provide, but what it is missing from my side is possibility to assign
```hcl
...
load_balancer_sku     = var.load_balancer_sku
load_balancer_profile = var.load_balancer_profile
...
```
in this module.

**Comment by zioproto** [comment]
@mielmat can you propose a PR with this change ?

You need to add `load_balancer_sku` and `load_balancer_profile` here:
https://github.com/Azure/terraform-azurerm-aks/blob/master/main.tf#L27

Define the variables:
https://github.com/Azure/terraform-azurerm-aks/blob/master/variables.tf

Validate that `load_balancer_profile` is specified only if `load_balancer_sku` is set to standard

You can also add an example:
https://github.com/Azure/terraform-azurerm-aks/tree/master/examples

That will run an e2e test, where you create a public IP with Terraform:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip

and you pass it in the `load_balancer_profile` block the IP as `outbound_ip_address_ids`

If you can draft a PR I will be happy to review it. Thanks

**Comment by mielmat** [comment]
Sure, I will try to raise PR for that.

**Comment by mazilu88** [comment]
Considering the PR is merged, when can we expect a release?

**Comment by zioproto** [comment]
hello @mazilu88 
we don't have a documented release cadence. I will open an issue for that.

@lonegunmanb  we can close this issue because the PR #277  is merged
