### ISSUE TITLE
Support for Auto-upgrade feature

### ISSUE THREAD

**Issue by alsikorski** [Azure/terraform-azurerm-aks#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hello,

I would like to have auto upgrade cluster feature

Thanks

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
module "aks" {
...
automatic_channel_upgrade  = "none | patch | rapid | node-image | stable"
...
}
```

### References

https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster

**Comment by zioproto** [comment]
Hello @alsikorski ,

thanks for proposing this new feature to the module. I have a question:

when setting `automatic_channel_upgrade` what happens to these other values ?

* `kubernetes_version`
* `orchestrator_version`

I mean setting `kubernetes_version`  for example to `1.25.2` and `automatic_channel_upgrade` to `patch`. If the autoupgrade will upgrade the cluster to `1.25.3`, will the next Terraform run complain for configuration drift ?
What is the best way to address this in the module ?

are you willing to propose a PR for this feature ?

thanks
