### ISSUE TITLE
Support for auto_scaler_profile

### ISSUE THREAD

**Issue by SubatomicHero** [Azure/terraform-azurerm-aks#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I would like to be able to have support for the `auto_scaler_profile` block. 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by zioproto** [comment]
Hello. Please could you confirm if the PR #278 fix this issue ? Thanks

**Comment by lonegunmanb** [comment]
I'm closing this issue since this feature has been implemented by #278. Please feel free to reopen it if you have any further question. Thanks @SubatomicHero.
