### ISSUE TITLE
Support for web application routing

### ISSUE THREAD

**Issue by rjsigma** [Azure/terraform-azurerm-aks#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Web app routing is a preview feature that seems to be a good option for managing ingress.  The support for web app routing is added to underlying terraform resources version 3.30, around November 2022.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
given the `web_app_routing` block only support a single attribute `dns_zone_id`, we could elevate the value as a top level variable.

variable "web_app_rounting_dns_zone_id" {
  type = string
  default = ""
  ...
}
...
resource "azurerm_kubenetes_cluster" {
  ...
  dynamic "web_app_routing" {
    for_each = var.web_app_routing_dns_zone_id != "" ? ["dns_zone_id"] : []
    content {
      dns_zone_id = var.web_app_routing_dns_zone_id
    }
  }
  ...
}
```

### References

- Azure documentation https://learn.microsoft.com/en-us/azure/aks/web-app-routing?tabs=without-osm
- terraform resource documentation https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#web_app_routing
- terraform resource support for web app routing: https://github.com/hashicorp/terraform-provider-azurerm/pull/18667

**Comment by lonegunmanb** [comment]
Thanks @rjsigma for opening this issue, I think we can arrange that in our next release.

**Comment by angshumanbagchi** [comment]
@lonegunmanb thanks for the very prompt response. Would you have an ETA for the next release? This will help us plan our work.
