### ISSUE TITLE
resource group creation

### ISSUE THREAD

**Issue by alextwlam-melco-resorts-com** [Azure/terraform-azurerm-aks#30]
Resource group creation is a bit random. 

There is node resource group, and aks resource group. Yet only node resource group is exported, while aks resource kept hidden. 

I would like the module to: 
1. Take resource group as parameter, so I can plugin module into bigger deployment; 
2. Put AKS and node into same resource group.

**Comment by sblack4** [comment]
I'm not sure if putting AKS and the nodes into the same RG is possible. See https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#node_resource_group

**Comment by alextwlam-melco-resorts-com** [comment]
> I'm not sure if putting AKS and the nodes into the same RG is possible. See https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#node_resource_group

Didn't know that, just throught it would be a good idea to put all project resources into the same container. Thanks for reminding.

**Comment by yupwei68** [comment]
Hi @alextwlam-melco-resorts-com Thanks for opening this issue. Currently, we have release a version v3.0 to import an existing resource group.
