### ISSUE TITLE
Are you looking for maintainers?

### ISSUE THREAD

**Issue by sblack4** [Azure/terraform-azurerm-aks#31]
This module needs TLC. I've been using it and can help maintain it if you guys need a hand.

**Comment by n01d** [comment]
Thank you for volunteering. I will reach out to the team within Microsoft that own the Azure terraform modules.

**Comment by adeshreddy** [comment]
Yes Please, Someone start shower some love on this module Please!! Recently Our organization got an Azure subscription looking to provision resource using these Super module

**Comment by dschniepp** [comment]
@n01d any update regarding the maintainer topic?

**Comment by sblack4** [comment]
It's not just this repo but it seems to be all of Azure's terraform code. It looks like we can still get stuff merged with two approving reviews.
