### ISSUE TITLE
Support for setting public_network_access_enabled

### ISSUE THREAD

**Issue by gaui** [Azure/terraform-azurerm-aks#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently it's not possible to set `public_network_access_enabled` as input into the AKS module. Therefor it uses the default value from the `public_network_access_enabled` resource itself. This makes it impossible to create a completely private cluster.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
module "aks" {
  source                            = "Azure/aks/azurerm"
  version                           = "x"
  ...
  public_network_access_enabled     = false
```

**Comment by zioproto** [comment]
hello @gaui 

thanks for raising this issue. Are you willing to propose a PR to expose `public_network_access_enabled` in the module ? I will be happy to review your PR.

thanks
