### ISSUE TITLE
Support for network policy calico

### ISSUE THREAD

**Issue by sandesh1994199** [Azure/terraform-azurerm-aks#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We would like to implement network policy as calico in our AKS deployment via terraform.

### New or Affected Resource(s)/Data Source(s)

azurerm_aks

**Comment by zioproto** [comment]
Hello @sandesh1994199 

as far as I understand you can already do this with the variable `network_policy`.

https://github.com/Azure/terraform-azurerm-aks/blob/f3b0be8421a36040b98371896ccf3df807756070/variables.tf#L624-L628

https://github.com/Azure/terraform-azurerm-aks/blob/f3b0be8421a36040b98371896ccf3df807756070/main.tf#L272

Could you please clarify if there is anything else that is not supported ?

Thanks

**Comment by lonegunmanb** [comment]
Hi @sandesh1994199, can @zioproto's answer solve your issue? If you have any further question, please let us know, thanks!

**Comment by lonegunmanb** [comment]
I'm closing this issue as no user response received. Please feel free to reopen it if you still have questions on this issue @sandesh1994199 .
