### ISSUE TITLE
Terraform plan output is the recreation of AKS Cluster

### ISSUE THREAD

**Issue by nidhi5885** [Azure/terraform-azurerm-aks#34]
I have implemented this modular approach in creation of AKS. Terraform Plan and Terraform Apply did their work, and I got my cluster up and running. But then by not doing any change to my AKS cluster, I executed Terraform plan again and as per it's output my AKS Cluster need to recreated(I don't know why it is happening, or why the Terraform is unable to match the states) 
To reproduce the issue: You just need to fork the repo,  make some required changes, execute terraform plan and terraform apply, when you see that the cluster is up and running. Again run terraform plan(without changing anything to the cluster)

**Comment by nidhi5885** [comment]
Any update on this? Help required.

**Comment by MichaelMcCoyTech** [comment]
I see this problem too!

**Comment by jmhill** [comment]
I ran into this problem as well (ran a terraform config that was calling only this module to test it out, and then after applying the terraform config immediately ran a `terraform plan` to verify everything was good), and noted that the cluster block in the plan had several fields marked as forcing the cluster to be recreated.

I don't have time to mess with it too much right now, but looking at the plan it seemed to me in my case like there was a problem with some sort of mapping between the deprecated `agent_pool_profile` argument that is used by this module, and the `default_node_pool` that is supposed to be used in newer versions of the azurerm provider (see https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#agent_pool_profile). At least in my case, the `terraform plan` output showed an attempt to change those fields to null on subsequent runs, when I had changed nothing about the config.

In my case I got around this by just using my own config from the tutorial (https://docs.microsoft.com/en-us/azure/terraform/terraform-create-k8s-cluster-with-tf-and-aks#define-a-kubernetes-cluster) which uses the new `default_node_pool`, and I had no problems. I suspect if you're using a newer version of terraform/azurerm provider you could fork this repo and change `agent_pool_profile` in the main.tf to `default_node_pool` (and update any of the arguments within that block as needed) and it'd probably work.

**Comment by yupwei68** [comment]
HI @nidhi5885 ,@jmhill , Thanks for opening this issue. We'll use default_node_pool in the next release v4.0 to support Azurerm 2.0. This problem will not appear in the release v4.0.
