### ISSUE TITLE
Paid sku replaced with Standard

### ISSUE THREAD

**Issue by wyattfry** [Azure/terraform-azurerm-aks#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.4

### Module Version

6.8.0

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks" {
  source                            = "Azure/aks/azurerm"
  version                           = "6.8.0"
  prefix                            = "foo"
  resource_group_name               = "rg"
  sku_tier                          = "Standard"
}
```

### tfvars variables values

```hcl
--
```

### Debug Output/Panic Output

```shell
│ Managed Cluster Name: "foo"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="SkuNotAvailable" Message="Standard managed cluster SKU tier is invalid. 'Paid' has been replaced by 'Standard' since v2023-02-01. "
│ 
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on .terraform/modules/aks/main.tf line 17, in resource "azurerm_kubernetes_cluster" "main":
│   17: resource "azurerm_kubernetes_cluster" "main" {
```

### Expected Behaviour

apply succeed

### Actual Behaviour

apply fails

### Steps to Reproduce

terraform apply

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#:~:text=to%20Free.-,Note%3A,where%20the%20value%20Paid%20must%20now%20be%20set%20to%20Standard.,-storage_profile%20%2D%20(Optional)%20A

**Comment by lonegunmanb** [comment]
This issue was caused by the [breaking change](https://github.com/hashicorp/terraform-provider-azurerm/pull/21256) introduced since AzureRM provider v3.51.0. We'll add a validation (which is also a breaking change) in this module's v7.0.0.

All this module's users should:

1. pin your `azurerm` provider's version to `< v3.51.0`.
2. or change `sku_tier` from `Paid` to `Standard`.
