### ISSUE TITLE
The given "for_each" argument value is unsuitable: "for_each" sets must not contain null values when using create_role_assignment_network_contributor

### ISSUE THREAD

**Issue by avekrivoy** [Azure/terraform-azurerm-aks#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.6

### Module Version

6.8.0

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment, azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
locals {
  node_pools = {
    monitoring = {
      name            = "monitoring"
      node_count      = 1
      vm_size         = "standard_d2ads_v5"
      max_pods        = 250
      node_labels = {
        "workload_type" = "monitoring"
      }
    }
  }
}

module "aks-cluster" {
  source                                     = "Azure/aks/azurerm"
  version                                    = "6.8.0"
  resource_group_name                        = azurerm_resource_group.rg.name
  location                                   = azurerm_resource_group.rg.location
  kubernetes_version                         = var.kubernetes_version
  orchestrator_version                       = var.kubernetes_version
  private_cluster_enabled                    = var.private_cluster_enabled
  prefix                                     = local.aks_prefix

  agents_pool_name                           = "system"
  agents_size                                = var.system_nodepool_agents_size
  agents_count                               = var.system_nodepool_agents_count
  agents_max_pods                            = var.system_nodepool_max_pods
  agents_availability_zones                  = var.system_nodepool_agents_availability_zones
  agents_labels                              = var.system_nodepool_agents_labels
  only_critical_addons_enabled               = var.only_critical_addons_enabled
  role_based_access_control_enabled          = var.role_based_access_control_enabled
  rbac_aad                                   = var.rbac_aad
  create_role_assignment_network_contributor = var.create_role_assignment_network_contributor

  network_plugin                             = var.network_plugin
  vnet_subnet_id                             = local.aks_vnet_subnet_id
  net_profile_service_cidr                   = var.net_profile_service_cidr
  net_profile_dns_service_ip                 = var.net_profile_dns_service_ip
  attached_acr_id_map                        = local.attached_acr_id_map
  maintenance_window                         = var.maintenance_window
  public_ssh_key                             = var.public_ssh_key
  # Addons
  key_vault_secrets_provider_enabled         = var.key_vault_secrets_provider_enabled
  secret_rotation_enabled                    = var.secret_rotation_enabled
  secret_rotation_interval                   = var.secret_rotation_interval
  tags                                       = local.common_tags

  node_pools                                 = local.node_pools

  depends_on = [
    module.vnet.vnet_subnets_name_id
  ]
}
```
```


### tfvars variables values

```hcl
variable "network_plugin" {
  default = "azure"
}

variable "network_policy" {
  default = "azure"
}

variable "create_role_assignment_network_contributor" {
  default = true
}
```
```


### Debug Output/Panic Output

```shell
│ Error: Invalid for_each set argument
│ 
│   on .terraform/modules/aks-cluster/main.tf line 582, in resource "azurerm_role_assignment" "network_contributor":
│  582:   for_each = var.create_role_assignment_network_contributor ? local.subnet_ids : []
│     ├────────────────
│     │ local.subnet_ids is set of string with 2 elements
│     │ var.create_role_assignment_network_contributor is true
│ 
│ The given "for_each" argument value is unsuitable: "for_each" sets must not contain null values.

```
```


### Expected Behaviour

When specifying additional node pools create_role_assignment_network_contributor = true should grant Contributor permission on AKS subnet

### Actual Behaviour

Apply fails when pod_subnet_id is not defined for node pool. Although this value is optional.
https://github.com/Azure/terraform-azurerm-aks/blob/main/locals.tf#L31

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

**Comment by zioproto** [comment]
Hello,

this is failing because `subnet_ids` is `null` in your scenario:

https://github.com/Azure/terraform-azurerm-aks/blob/647728060aaf7f845b90d9bf2e8ab47900ebe94e/locals.tf#L31-L37

In your steps to reproduce you have:

```
  vnet_subnet_id  = local.aks_vnet_subnet_id

```
Can you please share your code for ` local.aks_vnet_subnet_id` ? I need to understand why this value is `null`.

I agree we could implement a precondition that prevents to set `create_role_assignment_network_contributor` to `True` if the `local. subnet_ids` is null. 

In that case the role assignment is not needed: if all the vnets used are in the `MC_*` resource group, then there is already a role assignment in place with Contributor role scoped to the entire `MC_*` resource group. This means you don't need to create any additional role assignments.

Please share your `local.aks_vnet_subnet_id` to move forward. Thanks

**Comment by avekrivoy** [comment]
```
variable "vnet_address_space" {
  default = ["10.151.0.0/20"]
}

variable "vnet_subnet_names" {
  default = ["aks-dev", "shared-services"]
}

variable "vnet_subnet_prefixes" {
  default = ["10.151.0.0/21", "10.151.8.0/24"]
}

locals {
  aks_vnet_subnet_id = lookup(module.vnet.vnet_subnets_name_id, "aks-dev")
}

module "vnet" {
  source                                                = "Azure/vnet/azurerm"
  version                                               = "4.0.0"
  resource_group_name                                   = azurerm_resource_group.rg.name
  vnet_name                                             = var.vnet_name
  vnet_location                                         = azurerm_resource_group.rg.location
  use_for_each                                          = true
  address_space                                         = var.vnet_address_space
  subnet_names                                          = var.vnet_subnet_names
  subnet_prefixes                                       = var.vnet_subnet_prefixes
  subnet_enforce_private_link_endpoint_network_policies = local.vnet_subnet_enforce_private_link_endpoint_network_policies
  subnet_enforce_private_link_service_network_policies  = local.vnet_subnet_enforce_private_link_service_network_policies
  tags                                                  = local.common_tags
}
```
I suspect that it's due to pool.pod_subnet_id is null, hence the error "for_each" sets must not contain null values."

**Comment by lonegunmanb** [comment]
Hi @avekrivoy thanks for opening this issue, I think we should check whether your `local.aks_vnet_subnet_id` is `null` or not, but it's valid to set module's `vnet_subnet_id` variable to `null`, so I'll submit a pr to filter `null` out from `for_each`'s set.

**Comment by avekrivoy** [comment]
@lonegunmanb the problem is that during evaluation of the following code variable pool.pod_subnet_id is null. 
```
   subnet_ids = toset(flatten(concat([ 
     for pool in var.node_pools : [ 
       pool.vnet_subnet_id, 
       pool.pod_subnet_id 
     ] 
   ], [var.vnet_subnet_id]))) 
 } 
 ```
 Therefore, for loop iterates over valid pool.vnet_subnet_id vaule and "null" value of pool.pod_subnet_id. Hence the error.
 I've checked and explicitly defined pod_subnet_id variable for all node pools (both system and user). Everything worked as intended. So this fix should assume that pool.pod_subnet_id in fact can be empty, since (at least for AzureCNI) specifying vnet_subnet_id is enough to deploy a cluster

**Comment by lonegunmanb** [comment]
@avekrivoy Thanks for the update, yes we should upgrade this expression to filter `null` out.

**Comment by avekrivoy** [comment]
> @avekrivoy Thanks for the update, yes we should upgrade this expression to filter `null` out.

Perfect! Approximately, when will it be released?

**Comment by avekrivoy** [comment]
@lonegunmanb also, according to Azure documentation principal_id here is invalid
https://github.com/Azure/terraform-azurerm-aks/blob/647728060aaf7f845b90d9bf2e8ab47900ebe94e/main.tf#L677
Should be managed identity for an AKS cluster, not kubelet
https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#summary-of-managed-identities

**Comment by lonegunmanb** [comment]
> @lonegunmanb also, according to Azure documentation principal_id here is invalid
> 
> https://github.com/Azure/terraform-azurerm-aks/blob/647728060aaf7f845b90d9bf2e8ab47900ebe94e/main.tf#L677
> 
> 
> Should be managed identity for an AKS cluster, not kubelet
> https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#summary-of-managed-identities

Hi @avekrivoy thanks for pointing it out, would you please open a new issue so we can trace it?

**Comment by avekrivoy** [comment]
> > @lonegunmanb also, according to Azure documentation principal_id here is invalid
> > https://github.com/Azure/terraform-azurerm-aks/blob/647728060aaf7f845b90d9bf2e8ab47900ebe94e/main.tf#L677
> > 
> > Should be managed identity for an AKS cluster, not kubelet
> > https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#summary-of-managed-identities
> 
> Hi @avekrivoy thanks for pointing it out, would you please open a new issue so we can trace it?

https://github.com/Azure/terraform-azurerm-aks/issues/368
