### ISSUE TITLE
Support for Internal Load balancer

### ISSUE THREAD

**Issue by khurrambilalaurecon** [Azure/terraform-azurerm-aks#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

To add support for Load balancer Private IP option instead of pubic IP, It is required for cases where Azure Front Door or Application gateway connect to load balancer private IP using the Private Service link.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
dynamic "load_balancer_profile" {
  for_each = var.load_balancer_profile_enabled && var.load_balancer_sku == "standard" ? ["load_balancer_profile"] : []

  content {
    name                = var.load_balancer_name
    private             = var.load_balancer_private_mode
    sku                 = var.load_balancer_sku
    subnet_id           = var.private_subnet_id
    frontend_ip_address {
      name                  = "frontend-ip"
      private_ip_address    = var.frontend_private_ip_address
      private_ip_allocation = "Static"
      subnet_id             = var.private_subnet_id
    }
  }
}
```

**Comment by zioproto** [comment]
If I understand correctly your proposed change will create a private IP address to be used of OutBound traffic, not for inbound. The inbound IPs are created dinamically when Kubernetes Services are created.

For Azure Front Door to connect to load balancer private IP using the Private Service link, you can do this with Azure Private Link Service Intergration:

https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/

Here is a full example with Terraform:
https://github.com/zioproto/istio-aks-example/tree/main/istio-on-aks-with-front-door

The Kubernetes Service that creates the LoadBalancer with the private IP and is connected to private link:
https://github.com/zioproto/istio-aks-example/blob/a558670d26182d5dd005eeebee873a8a024908e8/istio-on-aks-with-front-door/istio-tf/istio.tf#L68-L79

Here the FrontDoor origin.
https://github.com/zioproto/istio-aks-example/blob/a558670d26182d5dd005eeebee873a8a024908e8/istio-on-aks-with-front-door/istio-tf/afd.tf#L49-L68

Please let me know if this solves your problem. I am not sure the change you are proposing is actually necessary.
