### ISSUE TITLE
Invalid principal id for "azurerm_role_assignment"  "network_contributor"

### ISSUE THREAD

**Issue by avekrivoy** [Azure/terraform-azurerm-aks#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.6

### Module Version

6.8.0

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
https://github.com/Azure/terraform-azurerm-aks/blob/647728060aaf7f845b90d9bf2e8ab47900ebe94e/main.tf#L677
```

### tfvars variables values

```hcl
.
```

### Debug Output/Panic Output

```shell
.
```

### Actual Behaviour

According to Azure documentation principal_id for "azurerm_role_assignment" "network_contributor" is invalid
https://github.com/Azure/terraform-azurerm-aks/blob/647728060aaf7f845b90d9bf2e8ab47900ebe94e/main.tf#L677

Should be managed identity for an AKS cluster, not kubelet
https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#summary-of-managed-identities

**Comment by zioproto** [comment]
@avekrivoy thanks for spotting this bug ! could you please test PR #369 ? Thanks !

**Comment by avekrivoy** [comment]
@zioproto I tried to deploy your fix with my current set of variables, but ran into an issue
```
│ Error: Resource precondition failed
│ 
│   on ../modules/terraform-azurerm-aks/main.tf line 453, in resource "azurerm_kubernetes_cluster" "main":
│  453:       condition     = !var.public_network_access_enabled || try(contains(var.api_server_authorized_ip_ranges, "0.0.0.0/32"), false)
│     ├────────────────
│     │ var.api_server_authorized_ip_ranges is null
│     │ var.public_network_access_enabled is true
│ 
│ When `public_network_access_enabled` is set to true, `0.0.0.0/32` must be added to `authorized_ip_ranges` in the `api_server_access_profile block`
│ (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#public_network_access_enabled).

```
I don't have public_network_access_enabled variable defined and private_cluster_enabled = true. Previously I've used 6.8.0 module version for my cluster deployment

**Comment by avekrivoy** [comment]
@zioproto I've deployed your fix and tested ingress-nginx chart with load balancer. It successfully issued an internal load balancer. So, I assume, all good here

**Comment by zioproto** [comment]
> Do I understand correctly that any pod in the cluster will inherit Network Contributor role attached to a managed identity if different workload/pod identity not specified?

If not using AKS workload identity, the Pod can get a token from the metadata server with the kubelet identity.

The AKS nodes have the following label:     `kubernetes.azure.com/kubelet-identity-client-id: <client_id>`

From the Pod you can find the client_id looking here:
```
curl -H "Metadata: true" 'http://169.254.169.254/metadata/instance?api-version=2021-12-13'
```
to get the token:
```
curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/&client_id=<clientID>' -H "Metadata: true"
```
So the Pods dont get a network contributor role, but they get a `AcrPull` role.
