### ISSUE TITLE
Error: retrieving contact for Keyvault: Keyvault. BaseClient#getcertificateContacts : failure sending request: Original error: context deadline exceeded

### ISSUE THREAD

**Issue by reshmav18** [Azure/terraform-azurerm-aks#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

N/A

### Module Version

N/A

### AzureRM Provider Version

N/A

### Affected Resource(s)/Data Source(s)

azurerm/keyvault

### Terraform Configuration Files

```hcl
resource "arurerm_key_vault" "keyvault"{
name = local.keyvault.name
location = var.deployment.target.location
resource_group_name =var.deployment.target.resource_group
enabled_for_disk_encryption= true
purge_protection_enabled = true
tenant_id= lookup(var.tenat_id, var.deployment.tenant)

sku_name ="premuim"

network_acls {
bypass= "Azureservices"
default_action= "deny"
virtual_network_subnet_ids =[]
ip_rules = var.allowed_ips
}

tags= local.tags_full

lifecycle{
ignore_changes =[
tags["created"]
]
}
}
```

### tfvars variables values

```hcl
N/A
```

### Debug Output/Panic Output

```shell
Error: retrieving contact for Keyvault: Keyvault. BaseClient#getcertificateContacts : failure sending request: Statuscode=0 -- Original error: context deadline exceeded
```

### Actual Behaviour

The customer is running a terraform script to re-create a AKS cluster which creates a PEP in Key Vault. The terraform script is listing the changes made, checking the KV config as below and then create a cluster associated with PEP. 

resource "arurerm_key_vault" "keyvault"{
name = local.keyvault.name
location = var.deployment.target.location
resource_group_name =var.deployment.target.resource_group
enabled_for_disk_encryption= true
purge_protection_enabled = true
tenant_id= lookup(var.tenat_id, var.deployment.tenant)

sku_name ="premuim"

network_acls {
bypass= "Azureservices"
default_action= "deny"
virtual_network_subnet_ids =[]
ip_rules = var.allowed_ips
}

tags= local.tags_full

lifecycle{
ignore_changes =[
tags["created"]
]
}
}

It is able to list the changes but when tries to check KV config failing with below error 

Error: retrieving contact for Keyvault: Keyvault. BaseClient#getcertificateContacts : failure sending request: Statuscode=0 -- Original error: context deadline exceeded

Able to see list changes in Azure activity logs, 

### Steps to Reproduce

The customer is running a terraform script to re-create a AKS cluster which creates a PEP in Key Vault. The terraform script is listing the changes made, checking the KV config as below and then create a cluster associated with PEP. 

resource "arurerm_key_vault" "keyvault"{
name = local.keyvault.name
location = var.deployment.target.location
resource_group_name =var.deployment.target.resource_group
enabled_for_disk_encryption= true
purge_protection_enabled = true
tenant_id= lookup(var.tenat_id, var.deployment.tenant)

sku_name ="premuim"

network_acls {
bypass= "Azureservices"
default_action= "deny"
virtual_network_subnet_ids =[]
ip_rules = var.allowed_ips
}

tags= local.tags_full

lifecycle{
ignore_changes =[
tags["created"]
]
}
}

It is able to list the changes but when tries to check KV config failing with below error 

Error: retrieving contact for Keyvault: Keyvault. BaseClient#getcertificateContacts : failure sending request: Statuscode=0 -- Original error: context deadline exceeded

Able to see list changes in Azure activity logs, 

Screenshot available

Reached out to Azure KeyVault team and suggestion was to reach out to Terreform Team

**Comment by zioproto** [comment]
You have a lot of typos in your steps to reproduce: `arurerm_key_vault`

I understand you are trying to deploy Azure Key Vault with Private Link.

Can you clarify why you opened this issue in the AKS module repository ? We dont have the `azurerm_key_vault` resource in this module.

Did you mean to open the issue in the terraform azurerm provider repo ? https://github.com/hashicorp/terraform-provider-azurerm

**Comment by lonegunmanb** [comment]
@reshmav18 thanks for reporting this issue to us, unfortunately I agree with @zioproto that it seems like a provider's issue, so I'm closing this issue. Please open a new issue on provider's repo, if you don't get a response for a while there, please feel free to ping me there and I'll take a look. Thanks for your understanding.

**Comment by reshmav18** [comment]
Thank you @lonegunmanb
