### ISSUE TITLE
Unable to access AKS cluster if setup using this module

### ISSUE THREAD

**Issue by mananpreetsingh** [Azure/terraform-azurerm-aks#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.6

### Module Version

6.8.0

### AzureRM Provider Version

3.58.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "aks_cluster" {
  location = var.aks_rg_location
  name     = var.aks_rg_name
}

module "aks" {
  source              = "Azure/aks/azurerm"
  resource_group_name = azurerm_resource_group.aks_cluster.name
  kubernetes_version                = "1.26.3"
  orchestrator_version              = "1.26.3"
  prefix                            = "aks-cluster-1-dns"
  cluster_name                      = "aks-cluster-1"
  network_plugin                    = "azure"
  vnet_subnet_id                    = module.vnet.vnet_subnets[1]
  os_disk_size_gb                   = 30
  sku_tier                          = "Free" # defaults to Free
  role_based_access_control_enabled = true
  rbac_aad                          = false
  rbac_aad_managed                  = false
  public_network_access_enabled     = false
  # api_server_authorized_ip_ranges   = ["0.0.0.0/32"]
  private_cluster_enabled          = false
  http_application_routing_enabled = false
  azure_policy_enabled             = false
  enable_auto_scaling              = true
  enable_host_encryption           = false
  agents_min_count                 = 1
  agents_max_count                 = 5
  agents_count                     = null
  agents_max_pods                  = 100
  agents_pool_name                 = "webnodepool"
  agents_availability_zones        = ["1", "2"]
  agents_type                      = "VirtualMachineScaleSets"
  agents_size                      = "Standard_D2_v4"

  ingress_application_gateway_enabled     = false
  ingress_application_gateway_name        = var.aks_agw_name
  ingress_application_gateway_subnet_cidr = "10.250.96.0/20"

  network_policy                 = "azure"
  net_profile_dns_service_ip     = "10.0.0.10"
  # net_profile_docker_bridge_cidr = "170.10.0.1/16"
  net_profile_service_cidr       = "10.0.0.0/16"

  depends_on = [module.vnet]
}
```

### tfvars variables values

```hcl
variable "aks_rg_location" {
  type    = string
  default = "canadacentral"
}

variable "aks_rg_name" {
  type    = string
  default = "aks-rg"
}
```

### Debug Output/Panic Output

```shell
I0601 17:38:35.267347   12329 round_trippers.go:570] HTTP Statistics: DNSLookup 1 ms Dial 0 ms TLSHandshake 238 ms ServerProcessing 117 ms Duration 359 ms
I0601 17:38:35.267356   12329 round_trippers.go:577] Response Headers:
I0601 17:38:35.267363   12329 round_trippers.go:580]     Nsp-Check-Request-Id: 52576e88-916d-40b7-bc59-884c084597fc
I0601 17:38:35.267370   12329 round_trippers.go:580]     Content-Type: application/json
I0601 17:38:35.267377   12329 round_trippers.go:580]     Content-Length: 102
I0601 17:38:35.267383   12329 round_trippers.go:580]     Date: Thu, 01 Jun 2023 23:38:34 GMT
I0601 17:38:35.267389   12329 round_trippers.go:580]     Server: envoy
I0601 17:38:35.267841   12329 request.go:1188] Response Body: {"error":{"code":"PublicNetworkAccess","message":"Inbound denied with PublicNetworkAccess=Disabled."}}
E0601 17:38:35.268274   12329 memcache.go:265] couldn't get current server API group list: unknown
I0601 17:38:35.268296   12329 cached_discovery.go:120] skipped caching discovery info due to unknown
```

### Expected Behaviour

I should be able to connect to the cluster.  If I create a cluster using the same settings manually I can access it, Not sure which setting am I missing.

### Actual Behaviour

Get the following error:

E0601 17:38:28.517543   12321 memcache.go:265] couldn't get current server API group list: unknown
E0601 17:38:28.676921   12321 memcache.go:265] couldn't get current server API group list: unknown
E0601 17:38:28.763925   12321 memcache.go:265] couldn't get current server API group list: unknown
E0601 17:38:28.849482   12321 memcache.go:265] couldn't get current server API group list: unknown
E0601 17:38:28.942884   12321 memcache.go:265] couldn't get current server API group list: unknown
Error from server (Forbidden): unknown

### Steps to Reproduce

terraform apply

**Comment by lonegunmanb** [comment]
Thanks @mananpreetsingh for reporting this issue to us, I believe this is the same issue as #370 and has been fixed by `7.0.0` (@zioproto would you please double confirm? Thanks!). Would you please upgrade the module version to `7.0.0` and try again? Thanks

---

Please be [advised](https://github.com/Azure/terraform-azurerm-aks/blob/main/NoticeOnUpgradeTov7.0.md) when you try to upgrade the module version.

**Comment by mananpreetsingh** [comment]
> Thanks @mananpreetsingh for reporting this issue to us, I believe this is the same issue as #370 and has been fixed by `7.0.0` (@zioproto please correct me if I'm wrong, thanks!). Would you please upgrade the module version to `7.0.0` and try again? Thanks
> 
> Please be [advised](https://github.com/Azure/terraform-azurerm-aks/blob/main/NoticeOnUpgradeTov7.0.md) when you try to upgrade the module version.

@lonegunmanb Thank you for the quick reply, seems 7.0.0 is not released yet. I only see the latest version `6.8.0` under releases or am I missing something?

**Comment by mananpreetsingh** [comment]
My bad I just double check I am using module 7.0.0, With `public_network_access_enabled` set to true There is a constraint on `api_server_authorized_ip_ranges` it takes only `0.0.0.0/32` which does not work either. Since it means it will only allow load balancer to communicate, nothing else. Should remove the condition to add other IP's.

**Comment by mananpreetsingh** [comment]
```

  public_network_access_enabled     = true
  api_server_authorized_ip_ranges   =["0.0.0.0/32","0.0.0.0/0"]
```

With the above config, I get the following error:

`Managed Cluster Name: "aks-cluster"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="Setting apiServerAuthorizedIPRange to 0.0.0.0/32 is not allowed with other IP ranges. Refer to https://aka.ms/aks/auth-ip-ranges for more details"`

**Comment by zioproto** [comment]
You need:
`api_server_authorized_ip_ranges = ["0.0.0.0/0"]` to open everything

please read the discussion here:
https://github.com/Azure/terraform-azurerm-aks/issues/370#issuecomment-1555945019

**Comment by zioproto** [comment]
I understand you are now using the module like this:
```
source  = "Azure/aks/azurerm"
version = "7.0.0"
```

You could use the latest `main` branch like this:

```
source = "github.com/Azure/terraform-azurerm-aks"
```
no need for `version`

**Comment by mananpreetsingh** [comment]
Thank you @zioproto  That resolved issue intermediately, and we have to ship the code to our customer, We like to pin the version so that with new changes it won't break, Do you know what is the timeline for the 7.1.0 release or is there a place where we can see?

**Comment by sujeetkp** [comment]
@zioproto - Without mentioning the version, the code may break in the future. How do we solve it ?

**Comment by zioproto** [comment]
You can pin a specific git commit:
https://developer.hashicorp.com/terraform/language/modules/sources#selecting-a-revision

example:
```
source = "github.com/Azure/terraform-azurerm-aks?ref=<commit_id>"
```

**Comment by lonegunmanb** [comment]
> Thank you @zioproto That resolved issue intermediately, and we have to ship the code to our customer, We like to pin the version so that with new changes it won't break, Do you know what is the timeline for the 7.1.0 release or is there a place where I can see?

@mananpreetsingh apology for the inconvenient, we'll publish `7.1.0` tomorrow.

**Comment by Vinaum8** [comment]
i used this blocked code and worked for me
```
source  = "Azure/aks/azurerm"
version = "7.1.0"
```

```
public_network_access_enabled   = true
api_server_authorized_ip_ranges = ["IP1", "IP2", "IP3"]
```

**Comment by mananpreetsingh** [comment]
Yeah it worked with this new version pushed.
