### ISSUE TITLE
Support for Proximity placement group when auto scaling is active

### ISSUE THREAD

**Issue by alsikorski** [Azure/terraform-azurerm-aks#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, there is no option to enable Proximity placement group feature when auto scaling is enabled. 

It would be nice to have additional property to pass "proximity_placement_group_id". 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
variable "agents_proximity_placement_group_id" {
  type        = string
  description = "The Proximity placement group ID - see https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/proximity_placement_group"
  default     = null
  nullable    = true
}

resource "azurerm_kubernetes_cluster" "main" {
  ...
  dynamic "default_node_pool" {
    ...
    content {
      ...
      proximity_placement_group_id = var.agents_proximity_placement_group_id
    }
  }
}
```

**Comment by lonegunmanb** [comment]
I like this idea @alsikorski, are you interested in submitting a pr to implement this feature?
