### ISSUE TITLE
provisioning windows nodes with custom scripts during cluster creation

### ISSUE THREAD

**Issue by ivanguravel** [Azure/terraform-azurerm-aks#40]
Hello!

Is there any approach to apply few lines of code during nodes creation process. Do you have some field like a `user_data` inside `agent_pool_profile` or `windows_profile` blocks?

I can solve the problem with helps ssh pipe to Windows node, but it's a bit complex, when i will try to autoscale nodepool.

Thank you!

**Comment by yupwei68** [comment]
Hi @ivanguravel ,Thansk for your suggestion. Currently, the field "user_data" is not available in [azurerm_kubernetes_cluster](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html).
