### ISSUE TITLE
Remove Support for setting public_network_access_enabled

### ISSUE THREAD

**Issue by zadigus** [Azure/terraform-azurerm-aks#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Unfortunately, the parameter you now support since #310 is not supported by azure anymore, as documented [here](https://github.com/Azure/AKS/issues/3690).

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
Remove the parameter.
```

### References

https://github.com/Azure/AKS/issues/3690

**Comment by zioproto** [comment]
@lonegunmanb according to this comment from the AKS PM: https://github.com/Azure/AKS/issues/3690#issuecomment-1590425190

probably the correct thing to do would be to revert #310 

It was not clear from the Terraform documentation that this was a preview feature in AKS.

**Comment by lonegunmanb** [comment]
The [`public_network_access_enabled`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#public_network_access_enabled) argument is a ForceNew argument, removing it directly from the module could cause a cluster recreation.

I think the only thing we can do now is mark the corresponding variable as deprecated.

**Comment by lonegunmanb** [comment]
Still in negotiation, the service team wants to remove this property.

**Comment by fsismondi** [comment]
@lonegunmanb  do you have any news regarding the negotiation?

**Comment by zadigus** [comment]
As far as I know the property is deprecated in azurerm provider version 3.75.0, so it seems to be heading towards the right direction

**Comment by chrisjohnson00** [comment]
When will this be removed? 
I'd love to get this warning out of my CD executions.

**Comment by lonegunmanb** [comment]
@fsismondi @zadigus @chrisjohnson00 Thanks for asking, our next major version for this module would be `8.0`, in this version upgrade we can introduce breaking changes, so I'd like to add `public_network_access_enabled` into `ignore_changes` to avoid recreation.

Our major goal for `8.0` is adding a new provider and resource [`modtm`](https://github.com/Azure/terraform-provider-modtm) so we can collect some anonymous module usage telemetry data, but we've been blocked by some issues. We're still working on it, once we can release our new provider, we'll proceed `8.0`, and `public_network_access_enabled` would be removed.

**Comment by zioproto** [comment]
With PR #485 we are ignoring the `public_network_access_enabled`. We are missing a second PR to completely remove it. Only then we can close this issue.
