### ISSUE TITLE
Updating var.kubernetes_version or var.orchestrator_version does not update kubernetes version of the system pools

### ISSUE THREAD

**Issue by fleetwoodstack** [Azure/terraform-azurerm-aks#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.2

### Module Version

7.1.0

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

var.kubernetes_version / var.orchestrator_version

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "7.1.0"
  ....

 kubernetes_version                         = var.kubernetes_version
 node_pools = var.node_pools
  ....
}
```

### tfvars variables values

```hcl
var.kubernetes_version
var.orchestrator_version
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

In Azure, the system pools should be updated with the kubernetes version specified, not just the nodes specified in var.node_pools.

### Actual Behaviour

When updating both var.kubernetes_version and var.orchestrator_version, the kubernetes versions of the system pools don't get changed. The versions of any extra nodes specified in var.node_pools DO get changed, however the system pools don't.

### Steps to Reproduce

Update var.kubernetes_version/var.orchestrator_version whilst also having extra node pools specified in var.node_pools.

### Important Factoids

None

**Comment by lonegunmanb** [comment]
Hi @fleetwoodstack thanks for opening this issue.

>When updating both var.kubernetes_version and var.orchestrator_version, the kubernetes versions of the system pools don't get changed. The versions of any extra nodes specified in var.node_pools DO get changed, however the system pools don't.

May I ask what is `kubernetes versions` of the system pools and extra nodes? Could you please point out the corresponding resource argument? Thanks!

**Comment by zioproto** [comment]
@fleetwoodstack Is this happening for minor version upgrades or patch version upgrades ? Could you please provide the reproduction steps with actual values ? thank you

**Comment by lonegunmanb** [comment]
I'm closing this issue since no response from the user @fleetwoodstack , please feel free to reopen it if you have any further questions.

**Comment by fleetwoodstack** [comment]
Sorry for late reply - my notifications were going to an old email.

@lonegunmanb the last time this happened (today) the kubernetes version was 1.26 and we tried upgrading this to 1.27. No changes were reported in the terraform plan. We had to upgrade this manually in the portal instead.

Here is the the same block but with the values, does that help? Can you replicate at all?
```
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "7.3.2"

  ...

  kubernetes_version                         = "1.26"
  automatic_channel_upgrade                  = "patch"

  ...

  # Node Pools
  node_pools = {
    name                  = "myexample"
    vm_size               = "Standard_F8s_v2"
    orchestrator_version  = "1.26"
    upgrade_settings = {
      max_surge = 25
    }
  }
}
```

@zioproto this is happening for minor version upgrades. We just upgraded from kubernetes_version 1.26 to 1.27 and the same thing happened (we had to manually upgrade them in the azure portal).

**Comment by fleetwoodstack** [comment]
@zioproto that was it! Thank you so much!!
