### ISSUE TITLE
Log analytics workspaces was not found

### ISSUE THREAD

**Issue by ghost** [Azure/terraform-azurerm-aks#411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.6

### Module Version

7.2.0

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0.0"
    }
  }
}

variable "subscription_id_1" {}
variable "subscription_id_2" {}

provider "azurerm" {
  features {}

  subscription_id = var.subscription_id_1
}

provider "azurerm" {
  alias = "log"

  features {}

  subscription_id = var.subscription_id_2
}

resource "azurerm_resource_group" "log" {
  name     = "log-347347347"
  location = "West Europe"

  provider = azurerm.log
}

resource "azurerm_log_analytics_workspace" "log" {
  name                = "log-856785685468"
  location            = azurerm_resource_group.log.location
  resource_group_name = azurerm_resource_group.log.name

  provider = azurerm.log
}

resource "azurerm_resource_group" "aks" {
  name     = "aks-34574357457"
  location = "West Europe"
}

module "aks" {
  source                          = "Azure/aks/azurerm"
  version                         = "7.2.0"
  resource_group_name             = azurerm_resource_group.aks.name
  prefix                          = "425867245986"
  rbac_aad                        = false
  log_analytics_workspace_enabled = true
  log_analytics_workspace = {
    id   = azurerm_log_analytics_workspace.log.id
    name = azurerm_log_analytics_workspace.log.name
  }

  depends_on = [azurerm_resource_group.aks]
}
```

### tfvars variables values

```hcl
subscription_id_1 = ""
subscription_id_2 = ""
```

### Debug Output/Panic Output

```shell
╷
│ Error: log analytics workspaces "log-856785685468" (Resource Group "log-347347347") was not found
│ 
│   with module.aks.data.azurerm_log_analytics_workspace.main[0],
│   on .terraform/modules/aks/main.tf line 725, in data "azurerm_log_analytics_workspace" "main":
│  725: data "azurerm_log_analytics_workspace" "main" {
│ 
╵
```

### Expected Behaviour

Provisioning aks cluster by providing an existing log_analytics_workspace from another subscription should succeed.

### Actual Behaviour

Provisioning aks cluster fails.

**Comment by lonegunmanb** [comment]
Hi @dkronhardt-juris thanks for opening this pr, unfortunately this module is designed for single subscription use for now, so in the module's code we didn't support multiple subscriptions.

I'll keep this issue open and try to figure out a solution if I can, but I can't promise a solution. Apology for your inconvenience.

**Comment by dkronhardt-juris** [comment]
@lonegunmanb but it was working in version 6.7.0 of the module. Now we cannot upgrade the module anymore.

**Comment by lonegunmanb** [comment]
I see, apology for your inconvenience @dkronhardt-juris, I'll see what I can to to mitigate this issue for you.
