### ISSUE TITLE
Missing support for "maintenance_window_node_os" and "node_os_channel_upgrade"

### ISSUE THREAD

**Issue by AugustBrzuzy** [Azure/terraform-azurerm-aks#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

From what I can see there are such attributes available to be called in azurerm_kubernetes_cluster: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster
but cannot be found in this module. 

I suppose these features in Azure and analogical attributes in azurerm are somewhat new but is there any ongoing process to introduce those in your main.tf??
cheers!

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by zioproto** [comment]
Hello,
the Upgrade Maintenance Schedule feature is still in preview:

* https://learn.microsoft.com/en-us/azure/aks/planned-maintenance
* https://github.com/Azure/AKS/issues/2983

**Comment by devopsvnext** [comment]
Hi,

The Upgrade Maintenance Schedule feature went GA 21st August 2023, so the preview feature label should probably be removed:

https://github.com/Azure/AKS/issues/2983#issuecomment-1688486537

It would be fantastic to have configuration of this supported via terraform.

**Comment by lonegunmanb** [comment]
@devopsvnext Thanks for letting me know this good news! Yeah, now we're good to bring this feature on!

**Comment by daximillian** [comment]
You have not yet added support for "node_os_channel_upgrade" and on the 2nd of September 2023 Azure changed the AKS node security patch policy from Unmanaged to None. Now if I want to set my node_os_channel_upgrade to Unmanaged I need to set it using the CLI. Is there a plan to support this in the module?
