### ISSUE TITLE
Support for confidental computin

### ISSUE THREAD

**Issue by xWhiteTonicx** [Azure/terraform-azurerm-aks#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Confidental compution support for use Intel SGX. It had been already addd to terraform provider. 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
variable "enable_confidential_computing" {
  type        = bool
  default     = false
  description = "(Optional) Should confidential compution be enabled?"
}

resource "azurerm_kubernetes_cluster" "main" {
   [..CUT..]
  dynamic "confidential_computing" {
    for_each = var.enable_confidential_computing ? ["confidential_computing"] : []
    content {
      sgx_quote_helper_enabled = true
    }
  }
   [..CUT..]
}
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#confidential_computing
https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-overview

**Comment by lonegunmanb** [comment]
I don't think this feature is a preview feature, so bring it on!
