### ISSUE TITLE
Missing Kubernetes Cluster Version

### ISSUE THREAD

**Issue by angelbarrera92** [Azure/terraform-azurerm-aks#43]
Hi Azure team!

I want to use a "verified" AKS terraform module to deploy some clusters. I went to the terraform registry page and i found this one: https://registry.terraform.io/modules/Azure/aks/azurerm/3.0.0 which is the "official" maintained by Microsoft Azure team.

Awesome. But currently i can not understand why i can not specify Kubernetes Version variable *(which is available both from web interface and terraform provider: https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#kubernetes_version)*

So...

The questions are:

1. Is this module currently maintained?
2. Is there a reason to not expose the Kubernetes Version variable?
3. Should i use another module?

Thanks!

**Comment by angelbarrera92** [comment]
v2 includes it. Should i use v2?
https://github.com/Azure/terraform-azurerm-aks/compare/v2.0...v3.0

**Comment by yupwei68** [comment]
hi @angelbarrera92 Thanks for opening this issue. On fact, the Kubernetes Cluster Version is removed because this field needs to be maintained from time to time (assign the default version value). Currently, only the latest version of Kubernetes Cluster is applied.  And we currently maintain it and have updated it to fit Azurerm 2.0. You could still use v2.0.

**Comment by angelbarrera92** [comment]
> hi @angelbarrera92 Thanks for opening this issue. On fact, the Kubernetes Cluster Version is removed because this field needs to be maintained from time to time (assign the default version value). Currently, only the latest version of Kubernetes Cluster is applied. And we currently maintain it and have updated it to fit Azurerm 2.0. You could still use v2.0.

So version 3 is not ready to use. Ok. I'll try with 2.0
