### ISSUE TITLE
Public load balancer created with load_balancer_profile_enabled = False

### ISSUE THREAD

**Issue by mangoleaf** [Azure/terraform-azurerm-aks#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.7

### Module Version

7.3.1

### AzureRM Provider Version

3.73.0

### Affected Resource(s)/Data Source(s)

azurerm_lb

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "7.3.1"

  load_balancer_profile_enabled = false
  load_balancer_sku = "standard"
  ...
}
```

### tfvars variables values

```hcl
No tfvars required. Just create a simple aks cluster but inclue the two load_balancer settings,.
```

### Debug Output/Panic Output

```shell
No output, its not a caught error.
```

### Expected Behaviour

A load balancer should not be created along with the AKS. 

### Actual Behaviour

A public load balancer with a public IP associated (named kubernetes) is provisioned even though, "load_balancer_profile_enabled" is set to false. I canprevent the load balancer from being provisioned by setting "load_balancer_sku = basic". However, I want my ingress service to create an internal load balancer at the time it is installed, if load_balancer_sku is set to basic I run into additional problems because a standard load balancer is required for a subnet with a NAT gateway. 

### Steps to Reproduce

terraform apply
check for load balancer in azure portal or cli

### Important Factoids

Running on Azure uswest2

**Comment by zioproto** [comment]
Hello, the `load_balancer_profile_enabled` variable is set to `false` by default, and it it is set to `true` to Enable a `load_balancer_profile` block. It is not a variable to disable the creation of the load balancer.

https://github.com/Azure/terraform-azurerm-aks/blob/f145f62a167dec3b70e7de3b7f204431453ff4d9/variables.tf#L527-L532

Here the details of the `load_balancer_profile` block:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#load_balancer_profile

You expectation of the of the LoadBalancer not being created in wrong.

**Comment by mangoleaf** [comment]
Hi Zioproto, thanks for the response.

I have read that documentation many times and compared with the source code of the module while trying to figure this problem out.

Sorry, if this isn't a bug then we can close it, but please let me just ask you this first. Is there a way to prevent a public load balancer from being created while still setting the sku to standard with this module?

**Comment by zioproto** [comment]
@mangoleaf https://learn.microsoft.com/en-us/azure/aks/egress-outboundtype

**Comment by mangoleaf** [comment]
Thank you, I didnt think to search for egress, I will close this issue.
