### ISSUE TITLE
Support for run_command_enabled

### ISSUE THREAD

**Issue by tanvp112** [Azure/terraform-azurerm-aks#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Please expose this argument in order to **disable** run command for the cluster. Currently, this is default to "true" and not changeable via the module.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
variable "run_command_enabled" {
  type        = bool
  default     = true
  description = "Enable run command for the cluster"
}
```

### References

N/A

**Comment by zioproto** [comment]
The feature is GA:
https://learn.microsoft.com/en-us/azure/aks/access-private-cluster?tabs=azure-cli

Interesting that this is enabled by default both in the Azure Portal and Az-Cli and there is no easy way to disable.

A workaround for az-cli is:
```
az resource update --id aks-resource-id --set apiServerAccessProfile.disableRunCommand=false
```

The Terraform provider implements this:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#run_command_enabled

**Comment by tanvp112** [comment]
Many thanks for the quick resolution! Hopefully your change will get merge and release the soonest.
