### ISSUE TITLE
var.maintenance_window.not_allowed should be optional

### ISSUE THREAD

**Issue by brk3** [Azure/terraform-azurerm-aks#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

v1.5.7

### Module Version

6.8.0

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
maintenance_window = {
     allowed = [
       {
         day   = "Monday",
         hours = [0, 5]
       },
     ]
   }
```

### tfvars variables values

```hcl
n/a
```

### Debug Output/Panic Output

```shell
The given value is not suitable for
 module.aks.module.aks.var.maintenance_window declared at
 .terraform/modules/aks.aks/variables.tf:604,1-30: attribute "not_allowed"
 is required.
```

### Expected Behaviour

I should be able to specify a `maintenance_window` without having to give a value for `not_allowed`. See https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#not_allowed

**Comment by lonegunmanb** [comment]
Hi @brk3 thanks for opening this pr, I've reviewed the [`maintenance_window`](https://github.com/Azure/terraform-azurerm-aks/blob/main/variables.tf#L642-L652), you can:

```hcl
maintenance_window = {
     allowed = [
       {
         day   = "Monday",
         hours = [0, 5]
       },
      not_allowed = []
     ]
   }
```

as a quick workaround. We'll try to add `optional` to this variable.
