### ISSUE TITLE
Support for Istio AKS AddOn

### ISSUE THREAD

**Issue by zioproto** [Azure/terraform-azurerm-aks#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

https://learn.microsoft.com/en-us/azure/aks/istio-about

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by lonegunmanb** [comment]
Hi @zioproto would you please check whether pr #468 could solve this issue? Thanks!

**Comment by zioproto** [comment]
I confirmed this is closed via #468 . thanks !
