### ISSUE TITLE
kube_dashboard is enabled, but provider can't disable it.

### ISSUE THREAD

**Issue by dargor** [Azure/terraform-azurerm-aks#47]
# Problem
`terraform apply` to spawn a brand new k8s cluster in a brand new resource group works fine, however each successive `terraform apply` wants to make the following modication to the cluster, even if I change nothing in my HCL files :
```
[...]
      ~ addon_profile {
          - kube_dashboard {
              - enabled = true -> null
            }
[...]
```
This does not seem to be manageable using module variables, or I missed it.

# Criticity
Mostly an annoyance as everything else works fine, would be fine to fix though.

# Versions
```
Terraform v0.12.26
+ provider.azurerm v2.15.0
+ provider.local v1.4.0
+ provider.tls v2.1.1
```

**Comment by yupwei68** [comment]
Hi @dargor , thanks for reporting this issue. I have opened an upstream issue to track it https://github.com/terraform-providers/terraform-provider-azurerm/issues/7984.

**Comment by ANGkeith** [comment]
``` hcl
module "aks" {
  source              = "Azure/aks/azurerm"
  resource_group_name = azurerm_resource_group.example.name
  client_id           = "your-service-principal-client-appid"
  client_secret       = "your-service-principal-client-password"
  prefix              = "prefix"
  vnet_subnet_id      = module.network.vnet_subnets[0]
  os_disk_size_gb     = 50
  enable_azure_policy = true
  sku_tier            = "Paid" # defaults to Free

  depends_on = [module.network]
  enable_kube_dashboard = true    <==================================== add this
}
```

**Comment by yupwei68** [comment]
Hi @ANGkeith Thanks for your reply. 
Since `enable_kube_dashboard` is not availble for all regions, we could not set this attribute `Computed`.
@dargor, You can set `enable_kube_dashboard` `true` to avoid the terraform plan difference. Related to https://github.com/Azure/terraform-azurerm-aks/pull/80.
