### ISSUE TITLE
New release to https://registry.terraform.io/modules/Azure/aks/azurerm/latest

### ISSUE THREAD

**Issue by tanvp112** [Azure/terraform-azurerm-aks#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

There have been a number of new features being merged recently, eg. run command, oms msi support, fips support for default node pool, image cleaner, service mesh profile. These are excellent features, please consider cut a new release to https://registry.terraform.io/modules/Azure/aks/azurerm/latest

### New or Affected Resource(s)/Data Source(s)

azurerm aks

### Potential Terraform Configuration

```hcl
NA
```

### References

Outdated: https://registry.terraform.io/modules/Azure/aks/azurerm/latest

**Comment by lonegunmanb** [comment]
We're very close to a new release.
