### ISSUE TITLE
Whether sku_tier of "azurerm_kubernets_cluster" supports "premium" functionality

### ISSUE THREAD

**Issue by sohwaje** [Azure/terraform-azurerm-aks#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The azcli command supports the following features when creating or updating an AKS.(Long Term Support (LTS))

1. sku_tier = premium
2. k8s-support-plan = AKSLongTermSupport

The example of the command is as follows. 

```
az aks create --resource-group myResourceGroup --name myAKSCluster --tier premium --k8s-support-plan AKSLongTermSupport --kubernetes-version 1.27

az aks update --resource-group myResourceGroup --name myAKSCluster --tier premium --k8s-support-plan AKSLongTermSupport
```

"sku_tier = premium", "k8s-support-plan = AKSLongTermSupport" is not currently supported for the "azurerm_kubernets_cluster" feature. Do you have any future support plans? I'm curious. In other words, I would like to know if you are planning to support the LTS feature or not.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by lonegunmanb** [comment]
Hi @sohwaje thanks for opening this issue! I've checked the [`azurerm_kubernetes_cluster`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#sku_tier) resource, it hadn't supported `premium` yet. I would suggest an issue in [`terraform-provider-azurerm`](https://github.com/hashicorp/terraform-provider-azurerm) repo first, once the resource support these features then we're good to bring them into this module.

Would you please close this issue and open a new one in the provider's repo? Thanks!

**Comment by zioproto** [comment]
The stable API is supporting this:
https://github.com/Azure/azure-rest-api-specs/blob/c1ba9df47907f9012ae14ca4616aed9e5665f9e5/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-10-01/managedClusters.json#L5777-L5785

However the docs have not been updated yet.
https://learn.microsoft.com/azure/aks/free-standard-pricing-tiers

Also the Azure Portal has not been updated yet.

The Terraform provider has this PR open:
https://github.com/hashicorp/terraform-provider-azurerm/pull/23970

Related provider issue:
https://github.com/hashicorp/terraform-provider-azurerm/issues/23972
