### ISSUE TITLE
Support for assignement of kubelet identity

### ISSUE THREAD

**Issue by luca-af** [Azure/terraform-azurerm-aks#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

When using the module to create an AKS instance, I cannot configure a custom kubelet identity.

From the resource `azurerm_kubernetes_cluster` I can specify the kubelet_identity parametes, but I can't find a similar configuration in this module.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by joshbsemperis** [comment]
its been merged, its in the documentation but not been added to the release or a release, this has caused me hours of debugging until i found it wasnt part of it, please do not add to documentation for a release if its not part of that release. When will it be released?
