### ISSUE TITLE
var.prefix is required

### ISSUE THREAD

**Issue by jrsherry** [Azure/terraform-azurerm-aks#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.5.7

### Module Version

7.5.0

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

azurerm_3.76.0

### Terraform Configuration Files

```hcl
Any of the examples in this repo with 'prefix' variable removed.
```

### tfvars variables values

```hcl
N/A
```

### Debug Output/Panic Output

```shell
Error: the "dns_prefix" must begin and end with a letter or a number, container only letters, numbers, and hyphens and be between 1 and 54 characters in length, got ""
```

### Expected Behaviour

Per the README, and variables.tf, prefix is optional.  However, if left unset, application of this module fails due to empty string being an invalid dns_prefix.

**Comment by jrsherry** [comment]
Closed the issue.  The documentation is correct in that the variable is optional when the cluster_log_analytics_workspace_name is set.  Unfortunately I had log_analytics_workspace_enabled set to false and didn't realize that I still needed to pass a workspace name to avoid the prefix error.

**Comment by Glaaj** [comment]
Seems to me like this still doesn't make much sense to "require" a name for a log analytics workspace when you disable creation.

Either the logic to disable the variable should be fixed or the documentation should provide this information since the error you get doesn't help much.

**Comment by zioproto** [comment]
> Seems to me like this still doesn't make much sense to "require" a name for a log analytics workspace when you disable creation.
> 
> Either the logic to disable the variable should be fixed or the documentation should provide this information since the error you get doesn't help much.

It is not about the log analytics.

It is used here:
https://github.com/Azure/terraform-azurerm-aks/blob/4729aee8c064da747186a14d6c3575c67e673692/main.tf#L24

**Comment by Glaaj** [comment]
Yes I've found the reason for it :)

However the description of the variable doesn't match with the behavior as that states the following:

```
"(Optional) The prefix for the resources created in the specified Azure Resource Group. Omitting this variable requires both `var.cluster_log_analytics_workspace_name` and `var.cluster_name` have been set."
```

And the fact that it's optional without a mention of `dns_prefix` using is what confused me at first. The field `dns_prefix` isn't a requirement according to the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#dns_prefix) but it's not intuitive this way, at least not for me.
