### ISSUE TITLE
Can't use this module with an identity

### ISSUE THREAD

**Issue by mcanevet** [Azure/terraform-azurerm-aks#50]
Because of [this](https://github.com/Azure/terraform-azurerm-aks/blob/94a406f508f8a80de9c2a493b1da52e6ea44d34e/main.tf#L33-L36), this module can't be used with a system assigned identity and requires a service principal.
I think it should be more generic.

**Comment by yupwei68** [comment]
Hi @mcanevet , thanks for opening this issue. Would you mind opening an issue [here](https://github.com/Azure/azure-rest-api-specs/issues) to notify the service team your suggestion?

**Comment by mcanevet** [comment]
@yupwei68 I'm not sure to understand why I should open an issue into the repo that hosts "The source for REST API specifications for Microsoft Azure". There is nothing to change in Azure's API. The problem is located in this Terraform module. Both the Azure API and the Azure Terraform provider supports creating an AKS cluster with a System Assigned Identity.
