### ISSUE TITLE
Ditch data.azurerm_resource_group from module

### ISSUE THREAD

**Issue by ohayak** [Azure/terraform-azurerm-aks#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi, I have this deployment:
```hcl
resource "azurerm_resource_group" "this" {
  name     = "${var.cluster_name}-aks"
  location = var.region
}

module "aks" {
  source  = "Azure/aks/azurerm"
  ...
}
```
I can't execute plan or apply because aks module requires an existing resource group. I checked the use of data.azurerm_resource_group , and it's used to get the location if not given as input.

I suggest to remove data.azurerm_resource_group and make location input required.

### New or Affected Resource(s)/Data Source(s)

data.azurerm_resource_group

**Comment by lonegunmanb** [comment]
@ohayak thanks for reporting this issue to us. In all examples we create the resource group along with module instance like you showed, have you assigned your resource group's name to module's `resource_group_name` variable? Could you please try the way like [this](https://github.com/Azure/terraform-azurerm-aks/blob/main/examples/startup/main.tf#L42)? Thanks!

**Comment by codymoss-bnet** [comment]
I got around this issue by petting a depends on the the module to tell it that the resource group needs to exist first. Still a workaround but it works.

**Comment by lonegunmanb** [comment]
I'm closing this issue since no response from @ohayak, please feel free to reopen it if you have any further questions.
