### ISSUE TITLE
Windows + CNI Overlay

### ISSUE THREAD

**Issue by JyrkiHei** [Azure/terraform-azurerm-aks#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.7.0

### Module Version

7.5.0

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

nodepool

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "7.5.0"

  resource_group_name = local.resource_group.name

  node_resource_group = "rg-${random_id.prefix.hex}-nodes"
  node_pools = {
    node1 = {
      name    = "pool1"
      vm_size = "Standard_B2ms"
      os_type = "Windows"
      os_sku  = "Windows2022"
      #   max_count = 2
      max_pods = 250
    }
  }

  prefix              = random_id.name.hex
  kubernetes_version  = "1.27"
  agents_type         = "VirtualMachineScaleSets"
  network_plugin      = "azure"
  network_plugin_mode = "overlay"
  network_policy      = "azure"

  rbac_aad = false # Just for debugging
}
```

### tfvars variables values

```hcl
none
```

### Debug Output/Panic Output

```shell
Error: Resource precondition failed
│
│   on .terraform\modules\aks\main.tf line 730, in resource "azurerm_kubernetes_cluster_node_pool" "node_pool":
│  730:       condition     = var.network_plugin_mode != "overlay" || each.value.os_type != "Windows"
│     ├────────────────
│     │ each.value.os_type is "Windows"
│     │ var.network_plugin_mode is "overlay"
│
│ Windows Server 2019 node pools are not supported for Overlay and Windows support is still in preview
```

### Expected Behaviour

Nodepool created with Windows 2022 server and Azure CNI Overlay

### Actual Behaviour

Precondition failure

### Steps to Reproduce

terraform plan

### References

AKS supports Windows 2019 & 2022 with Azure CNI Overlay.
https://github.com/Azure/AKS/issues/3843

Table for supported OSses: https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay?tabs=kubectl#differences-between-kubenet-and-azure-cni-overlay

**Comment by lonegunmanb** [comment]
Thanks for letting us know this feature is GA now @JyrkiHei , I'll make a pr to remove this precondition.
