### ISSUE TITLE
Log Analytics Workspace creation support set network insolation

### ISSUE THREAD

**Issue by RelaxingLoki475** [Azure/terraform-azurerm-aks#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Add capability to manage internet_ingestion_enabled and internet_query_enabled in Log Analytics Workspace creation 

### New or Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_log_analytics_workspace" "main" {
  count = local.create_analytics_workspace ? 1 : 0
  #Other configurations
  internet_ingestion_enabled = coalesce(var.log_analytics_workspace_internet_ingestion_enabled, true)
  internet_query_enabled     = coalesce(var.log_analytics_workspace_internet_query_enabled, true)
}
```

**Comment by zioproto** [comment]
hello @RelaxingLoki475 

is it also possible to pass the ID of an existing Log Analtycs workspace that you created with Terraform outside of this module:

https://github.com/Azure/terraform-azurerm-aks/blob/b7faaf63c4e1d5ce6a9c04d005baab6863e66282/variables.tf#L672-L681

In this case you are able to customize everything.

Why that approach would not work for you ?
We would like to keep the Log Analytics workspace created within the AKS module as simple as possible to maintain a smaller codebase. If you need more flexibility with the options you can always wring your own Log Analytics and just pass the ID.

Please let us know why this is not working for you, so we can find the best solution.

Thank you

**Comment by lonegunmanb** [comment]
Hi @RelaxingLoki475 I'm closing this issue since no response from the user, please feel free to reopen it if you have any further details want to share with us!
