### ISSUE TITLE
Support for node soak time

### ISSUE THREAD

**Issue by rgarcia89** [Azure/terraform-azurerm-aks#530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The following feature is currently not configurable using terraform but is already GA.
https://learn.microsoft.com/en-US/azure/aks/upgrade-aks-cluster?tabs=azure-cli#set-node-soak-time-value

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool/upgrade_settings

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "aks" {
...
  upgrade_settings {
    max_surge = 3
    node-soak-duration = 5
  }
}
```

### References

https://github.com/Azure/AKS/issues/3899

**Comment by zioproto** [comment]
Current status: waiting for Terraform provider support of the feature.

**Comment by Israphel** [comment]
azurerm 3.106.1 added support
