### ISSUE TITLE
Provide an option to choose the Storage Type for the OS disk used in Agent and node pools

### ISSUE THREAD

**Issue by anilkumarpodugu** [Azure/terraform-azurerm-aks#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

We have deployed around 6 to 8 AKS clusters in our azure subscriptions using terraform. We see that the System and User node pools were created in a node_resource_group and the instances are running with Image Reference OS disk as AKSUbuntu. And the Storage type is set to Premium_SSD_LRS. This value is set to default.
<img width="800" alt="github_new_feature" src="https://github.com/Azure/terraform-azurerm-aks/assets/69627867/1e2b7d1e-7dc5-4543-b9ba-fabdddd6ba51">

We would like to update the storage type to Standard_HDD_LRS or Standard_SSD_LRS or anyother option that Azure provides while creating a VM or VMSS.
A variable to hold the above value would really help.
If this request is not feasible. Would it be possible to provide an option to pass an inhouse or custom image reference, that could be used to spin up the nodes. 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool,azurerm_kubernetes_cluster

**Comment by RockyMM** [comment]
Hey, @anilkumarpodugu ,

This is not possible, AFAIK. If you check [AzAPI for managed clusters](https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters?pivots=deployment-language-bicep#managedclusterstorageprofile) you will see that the only option is to enable UltraSSD (which is not even available in all regions, AFAIK).

Again, in my knowledge, you cannot assign any VM or any VMSS to the AKS cluster. You need to create node pools from the portal or using AzAPI. Terraform is basically AzAPI client and cannot offer any  features that are not available in the AzAPI.

**Comment by anilkumarpodugu** [comment]
Hi @RockyMM,

Thanks for your reply.
I think my question is misunderstood. The User node pool or agent node pool that we configure for an AKS cluster are part of the node resource group and the pools are running as VMSS (configured using agents_type in azurerm_kubernetes_cluster resource type.
These VMSS are spawned while creating an AKS cluster using terraform and these are based on Source Image i.e., AKSUbuntu for Linux based agent and user node pools. And the Image is using Premium_SSD_LRS.
But when we create an AKS cluster using azure portal, we can have a user node pool using VMSS with AKSUbuntu image and it can use Standard_HDD_LRS or Standard_SSD_LRS.
This option to provide for node pools is missing.

Hope this helps to understand my requirement.
/Anil

**Comment by RockyMM** [comment]
Hi @anilkumarpodugu,

I am genuinely surprised how you chose a storage tier with a node image from the Azure portal. That option is not available to me:
<img width="775" alt="image" src="https://github.com/Azure/terraform-azurerm-aks/assets/1906065/da5e2e45-00a7-44d4-8cc7-2e7607d2121b">
<img width="766" alt="image" src="https://github.com/Azure/terraform-azurerm-aks/assets/1906065/9c2b585c-7f19-4d81-bba2-32aec9ff1e14">

I don't have such an option in the Azure portal, or maybe it's not transparent when choosing an Ubuntu image. However, I only see a single Ubuntu option for OS SKU, not several options. To help me understand your requirement, would you mind sharing a screenshot of how you are choosing a Storage Type when defining a user node pool for an AKS cluster?

Also, I have to reemphasize, that if something is not GA in AzAPI, then it is never part of this Terraform provider. If you take a look at many feature requests in this repo, you will see that many features are waiting for a GA to be adopted in this provider.

**Comment by zioproto** [comment]
@anilkumarpodugu please let me know if you need additional help here. Thanks

**Comment by lonegunmanb** [comment]
I'm closing this issue since no response from @anilkumarpodugu , please feel free to reopen it if you have any further questions.
