### ISSUE TITLE
Plan drift (update_settings) with azurerm == 3.104.2

### ISSUE THREAD

**Issue by Israphel** [Azure/terraform-azurerm-aks#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.5.5

### Module Version

8.0.0

### AzureRM Provider Version

3.104.2

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster.main

### Terraform Configuration Files

```hcl
Simple cluster with default node_pool
```

### tfvars variables values

```hcl
default
```

### Debug Output/Panic Output

```shell
~ default_node_pool {
            name                         = "default"
            # (25 unchanged attributes hidden)

          - upgrade_settings {}
        }
```

### Expected Behaviour

No changes should be found.

### Actual Behaviour

Wants to remove a map called **upgrade_settings**

**Comment by zioproto** [comment]
@Israphel this seems to be related to a specific version of the Azurerm provider. Could you please open an issue also at https://github.com/hashicorp/terraform-provider-azurerm/issues

Cc: @ms-henglu @stephybun
