### ISSUE TITLE
when trying to deploy aks cluster using this module it fails with the error "ServiceCidrOverlapExistingSubnetsCidr"

### ISSUE THREAD

**Issue by vilaspatel** [Azure/terraform-azurerm-aks#57]
### Below is my main.tf file . when i try to deploy this it deploys RG ,Vnet and Subnet but fails during AKS deployment 
**provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "aks" {
  name     = var.resourcegroupname
  location = var.location
  tags = {
    environment = "dev"
  }
}

module "network" {
  source              = "Azure/network/azurerm"
  resource_group_name = azurerm_resource_group.aks.name
  address_space       = "10.0.0.0/16"
  vnet_name           = "${var.prefix}-vnet"
  subnet_prefixes     = ["10.0.1.0/24"]
  subnet_names        = ["aks-main"]
  tags = {
    environment = "dev"
  }
  depends_on          = [azurerm_resource_group.aks]
}

module "aks" {
  source              = "Azure/aks/azurerm"
  version = "4.2.0"
  resource_group_name = azurerm_resource_group.aks.name
 client_id           = "your-service-principal-client-appid"
 client_secret       = "your-service-principal-client-password"
  prefix              = "${var.prefix}-aks"
  vnet_subnet_id      = module.network.vnet_subnets[0]
  os_disk_size_gb     = 126
  agents_count        = var.agents_count
  agents_size         = var.agents_size
  enable_log_analytics_workspace = false
  tags = {
    environment = "dev"
  }
  depends_on = [module.network]
}**

Error: creating Managed Kubernetes Cluster "prod-aks-aks" (Resource Group "elasticsearch-rgs"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ServiceCidrOverlapExistingSubnetsCidr" Message="The specified service CIDR 10.0.0.0/16 is conflicted with an existing subnet CIDR 10.0.1.0/24" Target="networkProfile.serviceCIDR"

  on .terraform/modules/aks/main.tf line 10, in resource "azurerm_kubernetes_cluster" "main":
  10: resource "azurerm_kubernetes_cluster" "main" {

**am I doing some thing wrong**

**Comment by Phrow** [comment]
I had the same issue. Somehow - even if the specified subnet should fit into the address-space, it doesn't work like this. If you're just after some defaults that work (but should be adapted for your prod-configuration), then you can go with:
- address_space = "10.1.0.0/16"
- subnet_prefixes = ["10.1.0.0/24"]

**Comment by yupwei68** [comment]
Hi @vilaspatel You can now specify the serviceCidr by variable `net_profile_service_cidr` to avoid this error. Related to https://github.com/Azure/terraform-azurerm-aks/pull/80

**Comment by michaeljguarino** [comment]
I believe this issue is still present with the configuration in the module's README, actually

**Comment by yupwei68** [comment]
Hi @michaeljguarino The service requires that the `net_profile_service_cidr` to be unique.

**Comment by michaeljguarino** [comment]
Yeah and the one in the example is actually contained within the subnet created in the network module

**Comment by yg57404** [comment]
User different CIDR Range and it works for me
use this range:-

["10.30.0.0/16"]
"10.30.1.0/24"

instead of this:

[10.0.0.0/16]
"10.0.1.0/24"
