### ISSUE TITLE
Hardcoded Kubernetes Version in Module

### ISSUE THREAD

**Issue by hairmare** [Azure/terraform-azurerm-aks#6]
I've been trying to spin up a cluster using the modules in the  development branch on this repo.

Currently it doesn't work due to the fact that the K8s version is hardcoded to a version not available on Azure anymore.
https://github.com/Azure/terraform-azurerm-aks/blob/7e38320cbec6d4e10b57780d65406c521b8e906d/modules/kubernetes-cluster/main.tf#L6

Is there any chance you could make this configurable as a variable? Would you accept a PR to this effect?

**Comment by n01d** [comment]
Thank you and sorry for not responding ealier.
