### ISSUE TITLE
Missing lifecycle Terraform meta-argument definition

### ISSUE THREAD

**Issue by 0xtvignoli** [Azure/terraform-azurerm-aks#610]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Description

I encountered an issue while trying to add a _lifecycle_ Terraform meta-argument to the AKS module. The intention was to ignore changes to the `microsoft_defender` attribute. However, when I included the following block in my configuration:

```
lifecycle {
  ignore_changes = [
    microsoft_defender
  ]
}
```
I've received the following error message during the plan/apply phase:
```
Error: Reserved block type name in module block

  on ../../main.tf line 118, in module "aks":
  118:   lifecycle {
  
The block type name "lifecycle" is reserved for use by Terraform in a future version.
```
## Steps to Reproduce

1. Create a Terraform configuration using the AKS module from the Azure provider.
2. Add the `lifecycle` block with `ignore_changes`.
3. Run `terraform plan` or `terraform apply`.

## Expected Behavior

The expected behavior is that Terraform should allow the use of the `lifecycle` meta-argument within the module without throwing an error, enabling me to ignore changes to the specified attribute.

## Actual Behavior

The actual behavior is that Terraform throws an error indicating that the `lifecycle` block type name is reserved for future use, preventing me from applying my configuration.

## Environment
Terraform version: _1.91_
AKS module version: _9.20_
Azure provider version: _3.117_

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl

```

**Comment by zioproto** [comment]
Hello, I am not understanding what you tried to do.

We do already use a lifecycle block in the module here:

https://github.com/Azure/terraform-azurerm-aks/blob/9087737408b0dfbe1b7e6a1fc5863ec160691ccd/main.tf#L562-L573

Could you be more specific about what you tried to implement ? Can you please provide a code example ? thanks

**Comment by 0xtvignoli** [comment]
Thank you for your response. Let me clarify my specific use case:

I'm trying to ignore changes to the `microsoft_defender` block in the AKS cluster configuration. Specifically, whenever I make changes to the cluster, Terraform proposes changing this configuration:

```
  # module.aks.module.aks.azurerm_kubernetes_cluster.main will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "main" {
        id                                  = "/subscriptions/id/resourceGroups/my-rg-int/providers/Microsoft.ContainerService/managedClusters/my-aks-int"
        name                                = "my-aks-int"
        tags                                = {
            "Environment" = "Integration"
            "Terraform"   = "true"
        }
        # (41 unchanged attributes hidden)

      - microsoft_defender {
          - log_analytics_workspace_id = "/subscriptions/id/resourcegroups/DefaultResourceGroup-WEU/providers/Microsoft.OperationalInsights/workspaces/id" -> null
        }

        # (11 unchanged blocks hidden)
    }
```

I tried adding a lifecycle block in my root module configuration:
```
module "aks" {
source = "Azure/aks/azurerm"
version = "9.2.0"
# ... other configuration ...
lifecycle {
    ignore_changes = [
      microsoft_defender
    ]
  }
```
However, this results in the error:
```
╷
│ Error: Reserved block type name in module block
│ 
│   on ../../main.tf line 125, in module "aks":
│  125:   lifecycle {
│ 
│ The block type name "lifecycle" is reserved for use by Terraform in a future version.
```

Could you please advise on the correct way to ignore changes to the `microsoft_defender` configuration within the AKS module? Should this be handled within the module itself rather than in the root configuration?

**Comment by zioproto** [comment]
in Terraform you cannot pass a lifecycle block to a module.

This specific `microsoft_defender` issue you mention was already discussed in https://github.com/Azure/terraform-azurerm-aks/issues/495

**Comment by zioproto** [comment]
@0xtvignoli  You might find useful this example of the `mapotf` tool that should solve your use case:

https://github.com/Azure/mapotf/tree/main/example/customize_aks_ignore_changes
