### ISSUE TITLE
In case anyone who is using `v4` o Windows might meet incorrect symbolic links error

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/terraform-azurerm-aks#614]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

Any version

### Module Version

9.3.0

### AzureRM Provider Version

~> 4.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "Azure/aks/azurerm//v4"
  version = "9.3.0"
}
```

### tfvars variables values

```hcl
none
```

### Debug Output/Panic Output

```shell
Any error message like `../variables.tf`
```

### References

This is not an actual bug, but for anyone who is using `v4` on Windows, if they haven't setup git's symbolic links correctly, they might meet weird error message contains `../variables.tf` or something match this pattern.

We can fix this issue easily according to [this answer](https://stackoverflow.com/a/59761201):

* Global setting: `git config --global core.symlinks true`
* Local setting: `git config core.symlinks true`

I'd like to record this issue in case anyone who might meet the same issue and is searching for the solution.

**Comment by Bourne-ID-Work** [comment]
IMO this may be useful to include on the readme to increase visibility/requirements to use this module on Windows.
