### ISSUE TITLE
Option to use calico as a network policy missing.

### ISSUE THREAD

**Issue by aleti-pavan** [Azure/terraform-azurerm-aks#63]
Hi, 

This is more of a request to have calico network policy as an option. We can't update the network policy once the cluster is created. Can we please have that available in the module ?

**Comment by yupwei68** [comment]
Hi @aleti-pavan , thanks for opening this issue.
We may enhance this feature in the future. But currently I could not give a plan for it. 
You're welcome to contribute to this module by raising a PR as well. 
If you want to open a PR, please add this feature into the test in test/fixture to integrate the test CI and add this feature in example in README.
