### ISSUE TITLE
Proposal - add cluster autoscaler support

### ISSUE THREAD

**Issue by es1o** [Azure/terraform-azurerm-aks#66]
Hello.
I'd like to use AKS cluster autoscaler to scale nodes in my cluster.

Could I create Pull Request with autoscaler support? Terraform module supports cluster autoscaling.

What do you think?

**Comment by yupwei68** [comment]
Hi @es1o , thanks for opening this issue. You're welcome to contribute to the module. Please add features into test/fixture to integrate CI and add features in example of README.
