### ISSUE TITLE
Proposal: Cluster-Name should follow Naming-recommendations or allow for change

### ISSUE THREAD

**Issue by Phrow** [Azure/terraform-azurerm-aks#69]
From the [Azure resource naming guidelines](https://docs.microsoft.com/de-de/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging) I understand the importance of a consistent naming across our resources. The azure [naming module](https://registry.terraform.io/modules/Azure/naming/azurerm/latest) documentation even suggests to be even stricter and merely use suffixes for resource names.

However, in this very aks module I can only define a prefix, no suffix and there's no option to otherwise influence the name for the cluster or the log analysis workspace.
In order to establish consistent naming amongst my resources, I would like to be able to have a stronger influence on the name - either by providing an additional suffix input or by adding a name input for both, the aks cluster as well as the log analytics workspace.

**Comment by yupwei68** [comment]
close for https://github.com/Azure/terraform-azurerm-aks/pull/84
