### ISSUE TITLE
Support for user_assigned_identity_id

### ISSUE THREAD

**Issue by mrWinston** [Azure/terraform-azurerm-aks#88]
Hi There!

The new release of the azurerm provider ( v2.44.0 [link](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.44.0) now has support for a user assigned identities, which makes managing a k8s cluster in a user defined network much easier ( cause you don't need to fiddle around with service principals ).

Are there already plans for upgrading to the new provider Version and to expose the neccessary configuration on a module level?

I'm also open to issue a PR myself, but i wanted to check in with the maintainers first.

**Comment by yupwei68** [comment]
Hi @mrWinston , thanks for opening this issue. 
We may enhance this feature in the future. But currently I could not give a plan for it. 
You're welcome to contribute to this module by raising a PR. 
If you want to open a PR, please add this feature into the test in test/fixture to integrate the test CI and add this feature in example in README.
