### ISSUE TITLE
Bug: Can not disable Managed AAD RBAC while enabling RBAC

### ISSUE THREAD

**Issue by beastob** [Azure/terraform-azurerm-aks#96]
Hi, when I try to disable managed AAD RBAC and keeping the RBAC enabled, I have the following error:
```
╷
│ Error: You must specify client_app_id and server_app_id and server_app_secret when using managed aad rbac (managed = false)
│ 
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on .terraform/modules/aks/main.tf line 10, in resource "azurerm_kubernetes_cluster" "main":
│   10: resource "azurerm_kubernetes_cluster" "main" {
│ 
╵
```
Here is may aks config setting:
```yaml
module "aks" {
  source                           = "Azure/aks/azurerm"
  version                          = "4.9.0"
  .....
  enable_role_based_access_control = true
  rbac_aad_managed                 = false
  ....
}
```

**Comment by yupwei68** [comment]
Hi @beastob  , thanks for opening this issue. According to the Terraform definition https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster. 
When you enable role based access control and you disabled managed, you must specify the client app id and server app id and server app secret
![image](https://user-images.githubusercontent.com/56525716/119105447-e7daf000-ba4f-11eb-8a5c-4696b7fb3e89.png)

**Comment by beastob** [comment]
Hi, thank you for your clarification. I am closing this issue.
